// 序幕·常山从戎 — print / 注释 / sep & end
export const ACT0 = {
  id: 'ch0', name: '序幕·常山从戎', emoji: '⚔️', color: '#8B1A1A',
  subtitle: '投公孙瓒，校场扬名',
  blurb: '赵云年少习武，于幽州投公孙瓒。校场之上，以 print 亮出名号，从此踏上纵横沙场之路。',
  missions: [
    { id: 'a0-m1', title: '亮出名号——print 基础', emoji: '📢' },
    { id: 'a0-m2', title: '战记如旁批——注释', emoji: '📝' },
    { id: 'a0-m3', title: '连续传令——sep 与 end', emoji: '📣' },
    { id: 'a0-boss', title: 'BOSS战·校场大比武', emoji: '⚔️' },
  ],
  steps: [
    // ── Mission 1: print ──────────────────────────────
    {
      id: 'a0-t1', type: 'teach', topicId: 'py-print', missionId: 'a0-m1',
      title: 'print() 函数',
      blurb: '把内容输出到屏幕——程序与你对话的第一步。',
      syntax: 'print(value)\nprint(value1, value2, ...)',
      example: 'print("吾乃常山赵子龙！")\nprint("龙胆枪", "白马", "银甲")',
      output: '吾乃常山赵子龙！\n龙胆枪 白马 银甲',
      note: '文字必须用引号包起来；多个值之间默认以空格分隔。',
      related: ['py-comments', 'py-variables'],
      story: '校场鼓响。点将台上，高声报出名号！',
    },
    {
      id: 'a0-c1', type: 'challenge', topicId: 'py-print', missionId: 'a0-m1',
      title: '自报家门',
      story: '鼓声雷动——报上名来！',
      lore: '赵云，字子龙，常山真定人，身长八尺，姿颜雄伟。初从义兵，后归公孙瓒。',
      task: '输出（一字不差）：\n吾乃常山赵子龙！',
      starter: '# 写一行 print，亮出名号\n',
      expect: '吾乃常山赵子龙！',
      hints: ['用 print()', 'print("吾乃常山赵子龙！")', '注意感叹号是中文全角！'],
      reward: '威名初振！print 掌握。',
    },
    // ── Mission 2: 注释 ────────────────────────────────
    {
      id: 'a0-t2', type: 'teach', topicId: 'py-comments', missionId: 'a0-m2',
      title: '注释 #',
      blurb: '井号 # 开头的行，Python 完全跳过——是写给自己看的旁批。',
      syntax: '# 单行注释，Python 跳过此行\ncode  # 行内注释',
      example: '# 这是赵云的第一招\nprint("龙胆枪法")  # 枪法出招',
      output: '龙胆枪法',
      note: '注释不影响运行；好的注释解释"为什么"，而非"是什么"。',
      related: ['py-print'],
      story: '兵书旁批——不执行，只留记。',
    },
    {
      id: 'a0-c2', type: 'challenge', topicId: 'py-comments', missionId: 'a0-m2',
      title: '加上旁批',
      story: '在战令旁添注，让后人看懂！',
      task: '先写一行 # 注释（内容随意），再 print("常山赵子龙")。',
      starter: '# 在此处写你的注释\n# 然后在下方 print\n',
      expect: '常山赵子龙',
      hints: ['# 开头是注释', '然后 print("常山赵子龙")', '注释不影响输出'],
      reward: '旁批留记！注释使代码清晰。',
    },
    {
      id: 'a0-q1', type: 'quiz', missionId: 'a0-m2',
      question: '下列哪行代码会被 Python 执行？',
      options: ['# print("龙胆枪")', 'print("龙胆枪")  # 注释', '# 赵云出招', '以上都不执行'],
      answer: 1,
      explain: '行内注释（# 后半段）不影响前半段的 print 执行；纯注释行整行被跳过。',
    },
    // ── Mission 3: sep / end ───────────────────────────
    {
      id: 'a0-t3', type: 'teach', topicId: 'py-print-sep-end', missionId: 'a0-m3',
      title: 'print 的 sep 与 end 参数',
      blurb: 'sep 控制多值分隔符（默认空格），end 控制行尾字符（默认换行）。',
      syntax: "print(v1, v2, sep='分隔符', end='行尾')",
      example: "print('赵云','张飞','关羽', sep='|')\nprint('杀！', end=' ')\nprint('冲！')",
      output: '赵云|张飞|关羽\n杀！ 冲！',
      note: "end='' 让下一个 print 紧接在同一行。",
      related: ['py-print', 'py-str-basic'],
      story: '三路军令连发，一气呵成！',
    },
    {
      id: 'a0-c3', type: 'challenge', topicId: 'py-print-sep-end', missionId: 'a0-m3',
      title: '连续传令',
      story: '三军齐动，旗号用横线隔开！',
      task: "用一行 print，以 '-' 为分隔符输出：\n骑兵-步兵-弓兵",
      starter: "# 用 sep='-' 打印三支军队\n",
      expect: '骑兵-步兵-弓兵',
      hints: ["print('骑兵','步兵','弓兵', sep='-')", "sep='-' 放在值后面", "注意引号"],
      reward: '三路齐发！sep 参数用得漂亮。',
    },
    // ── BOSS: 校场大比武 ────────────────────────────────
    {
      id: 'a0-boss', type: 'boss', missionId: 'a0-boss',
      title: '校场大比武', bossName: '校尉张图', bossTaunt: '区区白身，竟敢挑战校尉！',
      story: '三轮对答，智取校尉！',
      lore: '公孙瓒麾下，诸将以武较高下，赵云初来乍到，须以实力服众。',
      bossHp: 3,
      challenges: [
        { id: 'b1', task: '输出：龙胆枪法，天下无双！', starter: '', expect: '龙胆枪法，天下无双！', hint: 'print("龙胆枪法，天下无双！")' },
        { id: 'b2', task: "用 sep='·' 输出：赵云·字子龙·常山人", starter: '', expect: '赵云·字子龙·常山人', hint: "print('赵云','字子龙','常山人', sep='·')" },
        { id: 'b3', task: "两行 print，用 end=' ' 让它们在同一行输出：赵云 子龙", starter: '', expect: '赵云 子龙', hint: "print('赵云', end=' ')\nprint('子龙')" },
      ],
      reward: '张图惨败！赵云威名传遍校场！牙门将军之路，由此开启。',
    },
  ],
}
