// 第一幕·风雪识君 — 变量 / 多重赋值 / 类型 / casting / 数字
export const ACT1 = {
  id: 'ch1', name: '第一幕·风雪识君', emoji: '🐴', color: '#2E5A3A',
  subtitle: '初遇刘备，后归之',
  blurb: '公孙瓒处，赵云初遇刘备，志同道合，引为知己。变量，是记录英雄名号与兵力的花名册。',
  missions: [
    { id: 'a1-m1', title: '花名册——变量', emoji: '📋' },
    { id: 'a1-m2', title: '一令多事——多重赋值', emoji: '⚡' },
    { id: 'a1-m3', title: '辨旗识号——数据类型', emoji: '🏷️' },
    { id: 'a1-m4', title: '粮草换算——类型转换', emoji: '🔄' },
    { id: 'a1-m5', title: '数字兵马——int/float/complex', emoji: '🔢' },
    { id: 'a1-boss', title: 'BOSS战·初归刘备', emoji: '🐴' },
  ],
  steps: [
    // ── 变量 ──────────────────────────────────────────
    {
      id: 'a1-t1', type: 'teach', topicId: 'py-variables', missionId: 'a1-m1',
      title: '变量',
      blurb: '变量是带名字的盒子——用 = 存值，随时取出。',
      syntax: '变量名 = 值\nname = "赵云"\ntroops = 3000',
      example: 'name = "赵云"\ntroops = 3000\nprint(name)\nprint(troops)',
      output: '赵云\n3000',
      note: '变量名不能以数字开头，不能含空格，区分大小写（Name 与 name 不同）。',
      related: ['py-data-types', 'py-multi-assign'],
      story: '初遇刘备，给将士登记造册——名号要记准！',
    },
    {
      id: 'a1-c1', type: 'challenge', topicId: 'py-variables', missionId: 'a1-m1',
      title: '点兵造册',
      story: '刘备令：记下将名与兵力！',
      task: '把 name 设为 "赵云"，troops 设为 3000，\n用 f-string 输出：我是 赵云，统兵 3000 人',
      starter: 'name = "赵云"\ntroops = 3000\n# 用 f-string 输出\n',
      expect: '我是 赵云，统兵 3000 人',
      hints: ['f"我是 {name}，统兵 {troops} 人"', 'print(f"我是 {name}，统兵 {troops} 人")', '引号前加 f'],
      reward: '花名册成！变量初掌握。',
    },
    // ── 多重赋值 ──────────────────────────────────────
    {
      id: 'a1-t2', type: 'teach', topicId: 'py-multi-assign', missionId: 'a1-m2',
      title: '多重赋值',
      blurb: '一行同时给多个变量赋值，或让多个变量共享同一值。',
      syntax: 'a, b, c = 1, 2, 3\nx = y = z = 0',
      example: 'general, horse = "赵云", "白马"\nprint(general, horse)\nhp = mp = 100\nprint(hp, mp)',
      output: '赵云 白马\n100 100',
      note: '左右数量必须对应（解包赋值）；交换变量：a, b = b, a。',
      related: ['py-variables'],
      story: '一令同下，兵将同时就位！',
    },
    {
      id: 'a1-c2', type: 'challenge', topicId: 'py-multi-assign', missionId: 'a1-m2',
      title: '同时造册',
      story: '一令点齐龙胆枪与白马！',
      task: '用一行多重赋值把 weapon 设为 "龙胆枪"，steed 设为 "白马"，\n再分别 print 两个变量。',
      starter: '# 一行完成两个变量赋值\n',
      expect: '龙胆枪\n白马',
      hints: ['weapon, steed = "龙胆枪", "白马"', 'print(weapon)\nprint(steed)', '顺序对应'],
      reward: '一令双成！多重赋值简洁高效。',
    },
    // ── 数据类型 ──────────────────────────────────────
    {
      id: 'a1-t3', type: 'teach', topicId: 'py-data-types', missionId: 'a1-m3',
      title: '数据类型与 type()',
      blurb: 'Python 中每个值都有类型；type() 可以查看。',
      syntax: 'type(值)',
      example: 'print(type("赵云"))     # str\nprint(type(3000))       # int\nprint(type(3.14))       # float\nprint(type(True))       # bool',
      output: "<class 'str'>\n<class 'int'>\n<class 'float'>\n<class 'bool'>",
      note: '主要类型：str（字符串）/ int（整数）/ float（浮点数）/ bool（布尔）/ list / dict。',
      related: ['py-casting', 'py-variables'],
      story: '旗号不同，辨认清楚——类型是数据的旗帜。',
    },
    {
      id: 'a1-c3', type: 'challenge', topicId: 'py-data-types', missionId: 'a1-m3',
      title: '辨旗识号',
      story: '查清兵力数字是哪种类型！',
      task: '打印 type(9999) 的结果。',
      starter: '# 打印 type(9999)\n',
      expect: "<class 'int'>",
      hints: ['print(type(9999))', "结果是 <class 'int'>", '整数的类型是 int'],
      reward: '旗号辨明！type() 在手，类型尽览。',
    },
    {
      id: 'a1-q1', type: 'quiz', missionId: 'a1-m3',
      question: 'type("赵云") 的返回值是？',
      options: ["<class 'int'>", "<class 'str'>", "<class 'bool'>", "<class 'list'>"],
      answer: 1,
      explain: '用引号括起来的值是字符串，type() 返回 <class \'str\'>。',
    },
    // ── 类型转换 ──────────────────────────────────────
    {
      id: 'a1-t4', type: 'teach', topicId: 'py-casting', missionId: 'a1-m4',
      title: '类型转换 (Casting)',
      blurb: '用 int() / float() / str() 在类型之间互相转换。',
      syntax: 'int(值)    # 转整数\nfloat(值)  # 转浮点\nstr(值)    # 转字符串',
      example: 'n = int("500")      # 字符串 → 整数\nf = float(3)        # 整数 → 浮点\ns = str(3000)       # 整数 → 字符串\nprint(n + 100, f, s + " 人")',
      output: '600 3.0 3000 人',
      note: 'int("3.14") 会报错；需先 float() 再 int()：int(float("3.14")) → 3。',
      related: ['py-data-types', 'py-numbers'],
      story: '粮草换算——斛变石，石换担，须得转换单位！',
    },
    {
      id: 'a1-c4', type: 'challenge', topicId: 'py-casting', missionId: 'a1-m4',
      title: '粮草换算',
      story: '"800" 是字符串，加 200 要先变整数！',
      task: '把字符串 "800" 转成整数，加上 200，打印结果。',
      starter: 's = "800"\n# 转成整数后加 200，打印结果\n',
      expect: '1000',
      hints: ['int(s) 转整数', 'print(int(s) + 200)', '结果是 1000'],
      reward: '换算准确！int() 类型转换掌握。',
    },
    // ── 数字 ──────────────────────────────────────────
    {
      id: 'a1-t5', type: 'teach', topicId: 'py-numbers', missionId: 'a1-m5',
      title: '数字：int / float / complex',
      blurb: 'Python 有三种数值类型：整数、浮点数、复数。',
      syntax: 'x = 10      # int\ny = 3.14    # float\nz = 1+2j    # complex（选学）',
      example: 'a = 7\nb = 2\nprint(a // b)   # 整除: 3\nprint(a % b)    # 取余: 1\nprint(a ** b)   # 乘方: 49\nprint(round(3.567, 2))  # 四舍五入: 3.57',
      output: '3\n1\n49\n3.57',
      note: '/ 除法结果始终是 float；// 整除结果是 int（向下取整）。',
      related: ['py-arithmetic', 'py-casting'],
      story: '兵马计数，从不含糊——整数点将，浮点算粮。',
    },
    {
      id: 'a1-c5', type: 'challenge', topicId: 'py-numbers', missionId: 'a1-m5',
      title: '兵马核算',
      story: '3000 骑兵分 7 队，每队几人，余几人？',
      task: '打印 3000 // 7（整除）和 3000 % 7（余数），各一行。',
      starter: '# 打印整除结果，再打印余数\n',
      expect: '428\n4',
      hints: ['print(3000 // 7)', 'print(3000 % 7)', '整除和取余各打印一行'],
      reward: '核算精准！整除与取余，排兵必备。',
    },
    // ── BOSS ──────────────────────────────────────────
    {
      id: 'a1-boss', type: 'boss', missionId: 'a1-boss',
      title: '初归刘备', bossName: '守营都尉田楷', bossTaunt: '汝不过一介武夫，哪懂点兵之道！',
      story: '归附刘备前，须过田楷三关考核！',
      lore: '界桥之战后，刘备随公孙瓒，赵云亦在其中。此时官渡之战尚早，天下三分雏形未现。',
      bossHp: 3,
      challenges: [
        { id: 'b1', task: '用 f-string 输出：将军赵云，统兵 5000 人', starter: 'name="赵云"\ntroops=5000\n', expect: '将军赵云，统兵 5000 人', hint: 'print(f"将军{name}，统兵 {troops} 人")' },
        { id: 'b2', task: 'a, b = 10, 20；把两个变量互换后，打印 a 和 b（各一行）', starter: 'a = 10\nb = 20\n# 互换后打印\n', expect: '20\n10', hint: 'a, b = b, a' },
        { id: 'b3', task: '把 "3500" 转成整数，加上 1500，打印结果', starter: 's = "3500"\n', expect: '5000', hint: 'print(int(s) + 1500)' },
      ],
      reward: '田楷折服！赵云正式归属刘备帐下——翻开三国最传奇的篇章！',
    },
  ],
}
