// 第二幕·军中文书 — 字符串全套
export const ACT2 = {
  id: 'ch2', name: '第二幕·军中文书', emoji: '📜', color: '#1A3A6E',
  subtitle: '博望坡随军，起草军令',
  blurb: '博望坡之战前，赵云随军参谋。军令文书字字千钧，字符串是将军的笔墨。',
  missions: [
    { id: 'a2-m1', title: '创建军令——字符串基础', emoji: '✍️' },
    { id: 'a2-m2', title: '截取情报——索引与切片', emoji: '✂️' },
    { id: 'a2-m3', title: '改写文书——修改方法', emoji: '🔧' },
    { id: 'a2-m4', title: '拆分传令——split / join', emoji: '🔗' },
    { id: 'a2-m5', title: '嵌入将名——f-string / format', emoji: '📋' },
    { id: 'a2-m6', title: '特殊字符——转义符', emoji: '🛡️' },
    { id: 'a2-m7', title: '查验印信——in / len', emoji: '🔍' },
    { id: 'a2-boss', title: 'BOSS战·博望坡令', emoji: '🔥' },
  ],
  steps: [
    // ── 字符串基础 ────────────────────────────────────
    {
      id: 'a2-t1', type: 'teach', topicId: 'py-str-basic', missionId: 'a2-m1',
      title: '字符串基础',
      blurb: '字符串是用引号括起来的文字序列，单/双/三引号均可。',
      syntax: "s1 = '单引号'\ns2 = \"双引号\"\ns3 = '''多行\n字符串'''",
      example: "order = '速援将军！'\nlong = '''第一行\n第二行'''\nprint(order)\nprint(long)",
      output: '速援将军！\n第一行\n第二行',
      note: '三引号字符串（\'\'\'...\'\'\'）可以跨多行，常用于多行文本或 docstring。',
      related: ['py-str-slice', 'py-str-methods'],
      story: '起草军令——文字须精准无误！',
    },
    {
      id: 'a2-c1', type: 'challenge', topicId: 'py-str-basic', missionId: 'a2-m1',
      title: '拟写军令',
      story: '军令已拟，打印备案！',
      task: '创建变量 order = "全军出击！"，然后 print 它。',
      starter: '# 创建 order 变量并打印\n',
      expect: '全军出击！',
      hints: ['order = "全军出击！"', 'print(order)', '变量名叫 order'],
      reward: '军令出征！字符串变量掌握。',
    },
    // ── 索引与切片 ────────────────────────────────────
    {
      id: 'a2-t2', type: 'teach', topicId: 'py-str-slice', missionId: 'a2-m2',
      title: '索引与切片',
      blurb: '用方括号按位置取字符；切片 [start:end] 取子串（不含 end）。',
      syntax: 's[0]         # 第一个字\ns[-1]        # 最后一个字\ns[2:5]       # 第3到第5个字\ns[:3]        # 前三个\ns[3:]        # 第4个起',
      example: 's = "常山赵子龙"\nprint(s[0])    # 常\nprint(s[-1])   # 龙\nprint(s[2:4])  # 赵子\nprint(s[:2])   # 常山',
      output: '常\n龙\n赵子\n常山',
      note: '索引从 0 开始；负索引从末尾倒数：-1 是最后一个。',
      related: ['py-str-basic', 'py-str-methods'],
      story: '截取情报关键字——精准定位！',
    },
    {
      id: 'a2-c2', type: 'challenge', topicId: 'py-str-slice', missionId: 'a2-m2',
      title: '截取将名',
      story: '从完整头衔里截出姓名两字！',
      task: '从字符串 "赵云将军" 中切出 "赵云"（前两个字）并打印。',
      starter: 's = "赵云将军"\n# 切出前两个字\n',
      expect: '赵云',
      hints: ['s[0:2] 取前两字', 'print(s[0:2])', 'start=0 可以省略：s[:2]'],
      reward: '将名截出！切片精准。',
    },
    // ── 修改方法 ──────────────────────────────────────
    {
      id: 'a2-t3', type: 'teach', topicId: 'py-str-methods', missionId: 'a2-m3',
      title: '字符串修改方法',
      blurb: '字符串方法不改变原字符串，而是返回新字符串。',
      syntax: 's.upper()          # 全大写\ns.lower()          # 全小写\ns.strip()          # 去两端空格\ns.replace(old,new) # 替换\ns.lstrip() / s.rstrip()  # 去单侧空格',
      example: 'code = "  ZILONG  "\nprint(code.strip())              # ZILONG\nprint(code.strip().lower())      # zilong\nreport = "张飞救主"\nprint(report.replace("张飞","赵云"))',
      output: 'ZILONG\nzilong\n赵云救主',
      note: '字符串是不可变类型，方法只返回新值，不修改原变量。',
      related: ['py-str-slice', 'py-str-split-join'],
      story: '改写文书——姓名写错，亟须更正！',
    },
    {
      id: 'a2-c3', type: 'challenge', topicId: 'py-str-methods', missionId: 'a2-m3',
      title: '更正错报',
      story: '战报写错将名，立刻改过！',
      task: '对 "关羽截江" 用 replace 把"关羽"换成"赵云"，打印新字符串。',
      starter: 'report = "关羽截江"\n# 替换后打印\n',
      expect: '赵云截江',
      hints: ['report.replace("关羽","赵云")', 'print(report.replace("关羽","赵云"))', '原字符串不变，打印返回值'],
      reward: '更正完毕！replace 掌握。',
    },
    // ── split / join ──────────────────────────────────
    {
      id: 'a2-t4', type: 'teach', topicId: 'py-str-split-join', missionId: 'a2-m4',
      title: 'split() 与 join()',
      blurb: 'split 把字符串按分隔符拆成列表；join 把列表合并成字符串。',
      syntax: "s.split('分隔符')       # 拆分\n'连接符'.join(列表)    # 合并",
      example: "generals = '赵云,张飞,关羽'\nteam = generals.split(',')\nprint(team)\nprint(' & '.join(team))",
      output: "['赵云', '张飞', '关羽']\n赵云 & 张飞 & 关羽",
      note: 'split() 不传参数时按空白（空格/换行）分隔，自动去除多余空格。',
      related: ['py-str-methods', 'py-list-basics'],
      story: '拆分军令，再重新组合传达！',
    },
    {
      id: 'a2-c4', type: 'challenge', topicId: 'py-str-split-join', missionId: 'a2-m4',
      title: '拆令再组',
      story: '把逗号分隔的军报拆开，再用"·"重新合并！',
      task: "对 '骑兵,步兵,弓兵' 用 split(',') 拆成列表，\n再用 '·'.join() 合并，打印合并结果。",
      starter: "s = '骑兵,步兵,弓兵'\n# 拆开再合并\n",
      expect: '骑兵·步兵·弓兵',
      hints: ["parts = s.split(',')", "print('·'.join(parts))", '两步：先 split 再 join'],
      reward: '拆令再组！split 与 join 掌握。',
    },
    // ── f-string / format ─────────────────────────────
    {
      id: 'a2-t5', type: 'teach', topicId: 'py-str-fstring', missionId: 'a2-m5',
      title: 'f-string 与 format()',
      blurb: 'f-string（推荐）在引号前加 f，用 {} 嵌入变量；format() 用 {} 占位。',
      syntax: "f'文字 {变量}'\n'文字 {}'.format(变量)",
      example: "name = '赵云'\ntroops = 5000\nprint(f'将军 {name}，统兵 {troops} 人')\nprint(f'{troops:,} 兵马')  # 千位分隔符",
      output: '将军 赵云，统兵 5000 人\n5,000 兵马',
      note: 'f-string 里可以写表达式：f"{2+3}" 输出 5；{变量:.2f} 保留两位小数。',
      related: ['py-str-basic', 'py-str-format-advanced'],
      story: '军令嵌入将名，文书自动生成！',
    },
    {
      id: 'a2-c5', type: 'challenge', topicId: 'py-str-fstring', missionId: 'a2-m5',
      title: '生成文书',
      story: '军令模板一填，文书即成！',
      task: "rank='翊军将军', name='赵云', merit=680\n用 f-string 输出：翊军将军 赵云，战功 680",
      starter: "rank = '翊军将军'\nname = '赵云'\nmerit = 680\n# 用 f-string 输出\n",
      expect: '翊军将军 赵云，战功 680',
      hints: ['f"{rank} {name}，战功 {merit}"', 'print(f"{rank} {name}，战功 {merit}")', '变量放在 {} 里'],
      reward: '文书即成！f-string 掌握。',
    },
    // ── 转义字符 ──────────────────────────────────────
    {
      id: 'a2-t6', type: 'teach', topicId: 'py-str-escape', missionId: 'a2-m6',
      title: '转义字符',
      blurb: '反斜杠 \\ 引导特殊字符，让不可见或特殊含义的字符出现在字符串里。',
      syntax: '\\n  换行\n\\t  制表符（Tab）\n\\\\  反斜杠本身\n\\"  双引号',
      example: 'print("第一行\\n第二行")\nprint("姓名:\\t赵云")\nprint("他说：\\"子龙一身是胆也！\\"")',
      output: '第一行\n第二行\n姓名:\t赵云\n他说："子龙一身是胆也！"',
      note: 'r"原始字符串" 让反斜杠失去转义作用，常用于文件路径与正则表达式。',
      related: ['py-str-basic'],
      story: '密码中藏着换行符——须用转义才能解读！',
    },
    {
      id: 'a2-c6', type: 'challenge', topicId: 'py-str-escape', missionId: 'a2-m6',
      title: '解密文书',
      story: '军令分两行，用 \\n 换行！',
      task: '用一行 print 输出：\n出击！\n护主！\n（两行分别打印，使用 \\n 换行）',
      starter: '# 用一行 print 和 \\n 输出两行\n',
      expect: '出击！\n护主！',
      hints: ['print("出击！\\n护主！")', '\\n 在字符串内表示换行', '只用一个 print'],
      reward: '转义解密！\\n 换行掌握。',
    },
    // ── in / len ──────────────────────────────────────
    {
      id: 'a2-t7', type: 'teach', topicId: 'py-str-membership', missionId: 'a2-m7',
      title: 'in / not in / len()',
      blurb: 'in 检查是否包含子串；len() 统计字符数。',
      syntax: "'子串' in 字符串   # True/False\nlen(字符串)         # 字符个数",
      example: "order = '速援将军！'\nprint('将军' in order)    # True\nprint('骑兵' not in order) # True\nprint(len(order))         # 6",
      output: 'True\nTrue\n6',
      note: 'in 也用于列表、字典等——是 Python 通用的成员运算符。',
      related: ['py-str-methods', 'py-membership-in'],
      story: '验印信——"将军"在军令里吗？',
    },
    {
      id: 'a2-c7', type: 'challenge', topicId: 'py-str-membership', missionId: 'a2-m7',
      title: '查验印信',
      story: '核查军令：含有"赵云"才为真！',
      task: '对字符串 "赵云将军出击！"，\n打印 "赵云" in 该字符串 的结果。',
      starter: 's = "赵云将军出击！"\n# 打印 "赵云" in s\n',
      expect: 'True',
      hints: ['"赵云" in s 结果是 True', 'print("赵云" in s)', '包含则为 True'],
      reward: '印信核实！in 运算符掌握。',
    },
    // ── BOSS ──────────────────────────────────────────
    {
      id: 'a2-boss', type: 'boss', missionId: 'a2-boss',
      title: '博望坡令', bossName: '文官荀攸（出题）', bossTaunt: '字符串之道，岂是武夫能懂？',
      story: '博望坡用火攻之前，须传三道精准文书！',
      lore: '博望坡之战（207年），刘备用火计大败夏侯惇，赵云参战其中。此战是赵云跟随刘备后的早期胜仗之一。',
      bossHp: 3,
      challenges: [
        { id: 'b1', task: '从 "赵云将军" 切出最后两个字 "将军" 并打印', starter: 's="赵云将军"\n', expect: '将军', hint: 'print(s[2:]) 或 print(s[-2:])' },
        { id: 'b2', task: '把 "  子龙出击  " 去掉两端空格后转成大写，打印', starter: 's="  zilong  "\n', expect: 'ZILONG', hint: 'print(s.strip().upper())' },
        { id: 'b3', task: '用 f-string 输出：博望坡一战，斩敌 300 人', starter: 'battle="博望坡"\nkills=300\n', expect: '博望坡一战，斩敌 300 人', hint: 'print(f"{battle}一战，斩敌 {kills} 人")' },
      ],
      reward: '荀攸折服！字符串兵法，尽数掌握。博望坡火起，曹军大败！',
    },
  ],
}
