// 第三幕·粮道谋算 — 运算符全套
export const ACT3 = {
  id: 'ch3', name: '第三幕·粮道谋算', emoji: '⚖️', color: '#5A3A1A',
  subtitle: '赤壁前夕，筹措军资',
  blurb: '赤壁之战前，赵云督运粮草。兵马未动，粮草先行——算术与逻辑是调度之道。',
  missions: [
    { id: 'a3-m1', title: '粮草核算——算术运算符', emoji: '➕' },
    { id: 'a3-m2', title: '累加记功——赋值运算符', emoji: '📊' },
    { id: 'a3-m3', title: '比较情报——比较运算符', emoji: '⚖️' },
    { id: 'a3-m4', title: '多条件研判——逻辑 and/or/not', emoji: '🧠' },
    { id: 'a3-m5', title: '辨旗识帅——身份 is', emoji: '🔎' },
    { id: 'a3-m6', title: '阵中点名——成员 in', emoji: '📋' },
    { id: 'a3-m7', title: '先后有序——运算符优先级', emoji: '🎯' },
    { id: 'a3-boss', title: 'BOSS战·粮道争夺', emoji: '🌊' },
  ],
  steps: [
    // ── 算术 ──────────────────────────────────────────
    {
      id: 'a3-t1', type: 'teach', topicId: 'py-arithmetic', missionId: 'a3-m1',
      title: '算术运算符',
      blurb: 'Python 支持加减乘除、整除、取余和乘方六类算术运算。',
      syntax: '+ 加  - 减  * 乘  / 除（结果为float）\n// 整除  % 取余  ** 乘方',
      example: 'a, b = 17, 5\nprint(a + b)   # 22\nprint(a - b)   # 12\nprint(a * b)   # 85\nprint(a / b)   # 3.4\nprint(a // b)  # 3\nprint(a % b)   # 2\nprint(a ** 2)  # 289',
      output: '22\n12\n85\n3.4\n3\n2\n289',
      note: '/ 结果恒为 float；// 向下取整（-7//2 = -4，不是 -3）。',
      related: ['py-assignment-ops', 'py-numbers'],
      story: '1700 石粮分 5 路，各队几石，余几石？',
    },
    {
      id: 'a3-c1', type: 'challenge', topicId: 'py-arithmetic', missionId: 'a3-m1',
      title: '粮草核算',
      story: '3 车红药 + 4 车蓝药，每车 50 瓶，共多少瓶？',
      task: '计算 (3 + 4) * 50 并打印结果。',
      starter: '# 计算并打印\n',
      expect: '350',
      hints: ['print((3 + 4) * 50)', '括号先算', '结果是 350'],
      reward: '核算精准！算术运算掌握。',
    },
    // ── 赋值运算符 ────────────────────────────────────
    {
      id: 'a3-t2', type: 'teach', topicId: 'py-assignment-ops', missionId: 'a3-m2',
      title: '赋值运算符',
      blurb: '复合赋值运算符将算术与赋值合并：x += 1 等同于 x = x + 1。',
      syntax: 'x += n   # 加后赋值\nx -= n   # 减后赋值\nx *= n   # 乘后赋值\nx //= n  # 整除后赋值\nx **= n  # 乘方后赋值',
      example: 'merit = 100\nmerit += 50    # 等同 merit = merit + 50\nprint(merit)   # 150\nmerit *= 2\nprint(merit)   # 300',
      output: '150\n300',
      note: '没有 ++ 或 -- 运算符（不同于 C/Java）；用 += 1 / -= 1 代替。',
      related: ['py-arithmetic'],
      story: '每斩一敌，战功累加——用 += 记录！',
    },
    {
      id: 'a3-c2', type: 'challenge', topicId: 'py-assignment-ops', missionId: 'a3-m2',
      title: '累加战功',
      story: '斩将三次，每次 +30，从 100 开始累加！',
      task: 'merit = 100，用三次 merit += 30，打印最终 merit。',
      starter: 'merit = 100\n# 三次 merit += 30\n',
      expect: '190',
      hints: ['merit += 30', '共三次', 'print(merit)'],
      reward: '战功累积！+= 运算符掌握。',
    },
    // ── 比较 ──────────────────────────────────────────
    {
      id: 'a3-t3', type: 'teach', topicId: 'py-comparison', missionId: 'a3-m3',
      title: '比较运算符',
      blurb: '比较两个值，结果是 True 或 False。',
      syntax: '==  等于\n!=  不等于\n>   大于    >=  大于等于\n<   小于    <=  小于等于',
      example: 'a, b = 5000, 3000\nprint(a > b)   # True\nprint(a == b)  # False\nprint(a != b)  # True\nprint(b >= 3000)  # True',
      output: 'True\nFalse\nTrue\nTrue',
      note: '= 是赋值，== 是比较相等——混用会报错！',
      related: ['py-logical', 'py-if-else'],
      story: '我军 5000 vs 敌军 3000——孰强孰弱？',
    },
    {
      id: 'a3-c3', type: 'challenge', topicId: 'py-comparison', missionId: 'a3-m3',
      title: '兵力研判',
      story: '我军 3000 vs 敌军 5000，是否占优？',
      task: '打印 3000 >= 5000 的结果。',
      starter: '# 打印比较结果\n',
      expect: 'False',
      hints: ['print(3000 >= 5000)', '3000 不够 5000 大', '结果是 False'],
      reward: '研判准确！比较运算符掌握。',
    },
    // ── 逻辑 ──────────────────────────────────────────
    {
      id: 'a3-t4', type: 'teach', topicId: 'py-logical', missionId: 'a3-m4',
      title: '逻辑运算符 and / or / not',
      blurb: '组合多个条件：and 全真才真，or 一真即真，not 取反。',
      syntax: 'A and B   # 两者都为 True 才 True\nA or B    # 至少一个 True 即 True\nnot A     # 取反',
      example: 'rations = 600\ntroops = 1200\nprint(rations >= 500 and troops >= 1000)  # True\nprint(rations < 500 or troops > 1000)     # True\nprint(not (rations < 500))                # True',
      output: 'True\nTrue\nTrue',
      note: 'and 优先级高于 or；用括号让逻辑更清晰。',
      related: ['py-comparison', 'py-if-else'],
      story: '粮草足且兵力强——双重条件才能出战！',
    },
    {
      id: 'a3-c4', type: 'challenge', topicId: 'py-logical', missionId: 'a3-m4',
      title: '多条件研判',
      story: '粮草 >= 500 且兵力 >= 1000 才出战！',
      task: 'rations=600, troops=1200\n打印 (rations >= 500 and troops >= 1000)。',
      starter: 'rations = 600\ntroops = 1200\n# 打印逻辑结果\n',
      expect: 'True',
      hints: ['print(rations >= 500 and troops >= 1000)', '两个条件都满足，结果 True', 'and 要求全真'],
      reward: '研判完成！and 逻辑运算掌握。',
    },
    {
      id: 'a3-q1', type: 'quiz', missionId: 'a3-m4',
      question: 'True and False or True 的结果是？',
      options: ['True', 'False', 'None', '报错'],
      answer: 0,
      explain: 'and 优先于 or：先算 True and False = False，再算 False or True = True。',
    },
    // ── 身份 is ───────────────────────────────────────
    {
      id: 'a3-t5', type: 'teach', topicId: 'py-identity-is', missionId: 'a3-m5',
      title: '身份运算符 is / is not',
      blurb: 'is 判断两个变量是否指向同一个对象（地址相同），而非值相等。',
      syntax: 'a is b       # 同一对象？\na is not b   # 不是同一对象？',
      example: 'a = [1, 2]\nb = a         # b 指向同一列表\nc = [1, 2]    # c 是新列表\nprint(a is b)    # True\nprint(a is c)    # False\nprint(a == c)    # True（值相等）',
      output: 'True\nFalse\nTrue',
      note: '整数 -5~256 被 Python 缓存，is 可能返回 True；大整数不保证。建议用 is 只判断 None/True/False。',
      related: ['py-comparison', 'py-logical'],
      story: '眼前这面旗帜，是赵云的旗，还是同色别帜？',
    },
    {
      id: 'a3-c5', type: 'challenge', topicId: 'py-identity-is', missionId: 'a3-m5',
      title: '辨旗识帅',
      story: 'None 用 is 判断——这是 Python 惯例！',
      task: 'result = None\n打印 result is None 的结果。',
      starter: 'result = None\n# 打印 result is None\n',
      expect: 'True',
      hints: ['print(result is None)', 'None 用 is 判断', '结果是 True'],
      reward: '辨旗清楚！is 用于判断 None 是最佳实践。',
    },
    // ── 成员 in ───────────────────────────────────────
    {
      id: 'a3-t6', type: 'teach', topicId: 'py-membership-in', missionId: 'a3-m6',
      title: '成员运算符 in / not in',
      blurb: '判断元素是否存在于序列（字符串、列表、字典等）中。',
      syntax: "元素 in 序列\n元素 not in 序列",
      example: "team = ['赵云','张飞','关羽']\nprint('赵云' in team)        # True\nprint('曹操' not in team)    # True\nprint('龙' in '赵子龙')      # True",
      output: 'True\nTrue\nTrue',
      note: 'in 在字典上检查的是 key，不是 value：\'a\' in {\'a\':1} 为 True。',
      related: ['py-str-membership', 'py-list-basics'],
      story: '点将台上——赵云在不在这支队伍里？',
    },
    {
      id: 'a3-c6', type: 'challenge', topicId: 'py-membership-in', missionId: 'a3-m6',
      title: '阵中点名',
      story: '敌将在战场上！',
      task: "战场列表 battlefield = ['赵云','夏侯惇','张合']\n打印 '夏侯惇' in battlefield 的结果。",
      starter: "battlefield = ['赵云','夏侯惇','张合']\n# 打印判断结果\n",
      expect: 'True',
      hints: ["print('夏侯惇' in battlefield)", '在列表中为 True', 'in 成员运算符'],
      reward: '点名成功！in 运算符掌握。',
    },
    // ── 优先级 ────────────────────────────────────────
    {
      id: 'a3-t7', type: 'teach', topicId: 'py-precedence', missionId: 'a3-m7',
      title: '运算符优先级',
      blurb: '高优先级先计算；括号最高，可随时提升优先级。',
      syntax: '优先级由高到低（简化版）：\n** > 正负号 > * / // % > + - > 比较 > not > and > or',
      example: 'print(2 + 3 * 4)     # 14（先乘后加）\nprint((2 + 3) * 4)   # 20（括号提升）\nprint(not True or True and False)',
      output: '14\n20\nFalse',
      note: '有疑问时，加括号！括号让代码更清晰，也防止优先级陷阱。',
      related: ['py-arithmetic', 'py-logical'],
      story: '先斩哪路，后攻哪营——顺序决定胜负！',
    },
    {
      id: 'a3-q2', type: 'quiz', missionId: 'a3-m7',
      question: '2 ** 3 * 2 的结果是？',
      options: ['64', '16', '12', '8'],
      answer: 1,
      explain: '** 比 * 优先级高，先算 2**3=8，再算 8*2=16。',
    },
    // ── BOSS ──────────────────────────────────────────
    {
      id: 'a3-boss', type: 'boss', missionId: 'a3-boss',
      title: '粮道争夺', bossName: '曹将徐晃', bossTaunt: '断你粮道！看你如何支撑！',
      story: '赤壁前夕，曹将截道！三题取胜，护住粮草！',
      lore: '赤壁之战（208年）前，孙刘联军与曹操在长江对峙。此时赵云已是刘备重要亲卫将领。',
      bossHp: 3,
      challenges: [
        { id: 'b1', task: '打印 (500 + 300) * 2 的结果', starter: '', expect: '1600', hint: 'print((500+300)*2)' },
        { id: 'b2', task: 'x=10；x += 5，再 x *= 2，打印 x', starter: 'x = 10\n', expect: '30', hint: 'x+=5;x*=2;print(x)' },
        { id: 'b3', task: '打印 100>50 and 200!=300 的结果', starter: '', expect: 'True', hint: 'print(100>50 and 200!=300)' },
      ],
      reward: '徐晃退兵！粮道保住，赤壁决战在即。孙刘联军，胜！',
    },
  ],
}
