// 第四幕·长坂坡·单骑救主 — 布尔 / if / elif / 嵌套 / 三元 / match-case
export const ACT4 = {
  id: 'ch4', name: '第四幕·长坂坡·单骑救主', emoji: '🔥', color: '#6B1010',
  subtitle: '208年，当阳长坂，万军中护主',
  blurb: '建安十三年，当阳长坂。曹军如潮，赵云怀抱幼主，须臾之间作出无数决断——这就是条件判断。',
  extraTasks: [{
    id: 'a4-ex1',
    title: '青釭剑·match-case',
    task: 'Python 3.10+ 的现代写法——match-case！\nrank = "甲"\n用 match-case：rank=="甲"→打印"上将"；"乙"→"中将"；其余→"偏将"',
    starter: 'rank = "甲"\nmatch rank:\n    case "甲":\n        pass  # 改为 print("上将")\n    case "乙":\n        pass\n    case _:\n        pass\n',
    expect: '上将',
    hints: ['把 case "甲": 下的 pass 改成 print("上将")', 'match-case 是 Python 3.10 新语法', '_ 是通配符，相当于 else'],
    reward: '青釭剑法获悉！match-case 是赵云夺剑后解封的现代语法糖。',
  }],
  missions: [
    { id: 'a4-m1', title: '真假旗帜——布尔类型', emoji: '🏳️' },
    { id: 'a4-m2', title: '放行与止步——if / else', emoji: '🚪' },
    { id: 'a4-m3', title: '三路抉择——elif', emoji: '🔀' },
    { id: 'a4-m4', title: '阵中局——嵌套 if', emoji: '🎯' },
    { id: 'a4-m5', title: '一息决断——三元表达式', emoji: '⚡' },
    { id: 'a4-boss', title: 'BOSS战·七进七出（长坂坡）', emoji: '🔥' },
  ],
  steps: [
    // ── 布尔 ──────────────────────────────────────────
    {
      id: 'a4-t1', type: 'teach', topicId: 'py-bool', missionId: 'a4-m1',
      title: '布尔类型 bool',
      blurb: 'True / False 是 Python 两个布尔值，是条件判断的基础。',
      syntax: 'True   # 真\nFalse  # 假\nbool(值)  # 转换为布尔',
      example: 'print(bool(0))       # False\nprint(bool(1))       # True\nprint(bool(""))      # False（空串）\nprint(bool("赵云"))  # True（非空）\nprint(bool([]))      # False（空列表）',
      output: 'False\nTrue\nFalse\nTrue\nFalse',
      note: '0 / "" / [] / {} / None 都是 Falsy（假值）；其余都是 Truthy（真值）。',
      related: ['py-comparison', 'py-if-else'],
      story: '敌旗为真，友旗为假——一眼辨清！',
    },
    {
      id: 'a4-c1', type: 'challenge', topicId: 'py-bool', missionId: 'a4-m1',
      title: '辨旗真假',
      story: '空营必为假——布尔检验！',
      task: '打印 bool("") 和 bool("赵云") 的结果，各一行。',
      starter: '# 打印两个 bool 转换结果\n',
      expect: 'False\nTrue',
      hints: ['print(bool(""))', 'print(bool("赵云"))', '空串为 False，非空为 True'],
      reward: '旗帜辨清！布尔类型掌握。',
    },
    // ── if / else ─────────────────────────────────────
    {
      id: 'a4-t2', type: 'teach', topicId: 'py-if-else', missionId: 'a4-m2',
      title: 'if / else 条件语句',
      blurb: '条件为真执行 if 块，为假执行 else 块。',
      syntax: 'if 条件:\n    # 条件为真时执行\nelse:\n    # 条件为假时执行',
      example: 'hp = 80\nif hp > 50:\n    print("血气充沛，出战！")\nelse:\n    print("血气不足，退守！")',
      output: '血气充沛，出战！',
      note: '条件后必须有冒号 :；执行体必须缩进（通常 4 空格）。',
      related: ['py-bool', 'py-elif'],
      story: '见旗即判——是战是退，一念之间！',
    },
    {
      id: 'a4-c2', type: 'challenge', topicId: 'py-if-else', missionId: 'a4-m2',
      title: '守门决断',
      story: '年满 18 方可入营！',
      task: 'age = 20\n如果 age >= 18 打印"放行"，否则打印"止步"。',
      starter: 'age = 20\n# if/else 判断\n',
      expect: '放行',
      hints: ['if age >= 18:', '    print("放行")', 'else:\n    print("止步")'],
      reward: '守门精准！if/else 掌握。',
    },
    // ── elif ──────────────────────────────────────────
    {
      id: 'a4-t3', type: 'teach', topicId: 'py-elif', missionId: 'a4-m3',
      title: 'elif 多路分支',
      blurb: '当有多个互斥条件时，用 elif 代替嵌套 if—else。',
      syntax: 'if 条件1:\n    ...\nelif 条件2:\n    ...\nelif 条件3:\n    ...\nelse:\n    ...',
      example: 'enemies = 800\nif enemies > 1000:\n    print("突围！")\nelif enemies > 500:\n    print("护主撤离！")\nelse:\n    print("就地迎战！")',
      output: '护主撤离！',
      note: 'elif 是 else if 的缩写；Python 用缩进而不是大括号来划定代码块。',
      related: ['py-if-else', 'py-nested-if'],
      story: '三路大军，分三档判断——elif 一网打尽！',
    },
    {
      id: 'a4-c3', type: 'challenge', topicId: 'py-elif', missionId: 'a4-m3',
      title: '乱军辨敌',
      story: '敌兵数 800——护主撤离！',
      task: 'enemies = 800\n> 1000 打印"突围！"，> 500 打印"护主撤离！"，否则"就地迎战！"',
      starter: 'enemies = 800\n# if/elif/else 判断\n',
      expect: '护主撤离！',
      hints: ['if enemies > 1000:', 'elif enemies > 500:', 'else:'],
      reward: '判断准确！elif 掌握。',
    },
    // ── 嵌套 if ───────────────────────────────────────
    {
      id: 'a4-t4', type: 'teach', topicId: 'py-nested-if', missionId: 'a4-m4',
      title: '嵌套 if',
      blurb: 'if 内部可以再有 if，形成多层判断——但不要嵌套太深。',
      syntax: 'if 外层条件:\n    if 内层条件:\n        ...\n    else:\n        ...\nelse:\n    ...',
      example: 'alive = True\nhp = 30\nif alive:\n    if hp > 50:\n        print("强势出击")\n    else:\n        print("护主撤退")\nelse:\n    print("阵亡")',
      output: '护主撤退',
      note: '嵌套超过 3 层时，考虑用函数或 and/or 来简化逻辑。',
      related: ['py-elif', 'py-logical'],
      story: '活着才能战——先判生死，再判进退！',
    },
    {
      id: 'a4-c4', type: 'challenge', topicId: 'py-nested-if', missionId: 'a4-m4',
      title: '双重判断',
      story: '兵器充足且有马才能突围！',
      task: 'weapon=True, horse=True\n如果 weapon 为真，再判断 horse 是否为真：\n两者皆真 → "骑马突围！"；只有 weapon → "徒步冲锋！"；无武器 → "弃守！"',
      starter: 'weapon = True\nhorse = True\n# 嵌套 if 判断\n',
      expect: '骑马突围！',
      hints: ['if weapon:', '    if horse:', '        print("骑马突围！")'],
      reward: '双重判断通过！嵌套 if 掌握。',
    },
    // ── 三元表达式 ────────────────────────────────────
    {
      id: 'a4-t5', type: 'teach', topicId: 'py-ternary', missionId: 'a4-m5',
      title: '三元表达式（条件表达式）',
      blurb: '一行写完 if/else 的简洁版——A if 条件 else B。',
      syntax: '值A if 条件 else 值B',
      example: 'hp = 40\nstatus = "战！" if hp > 50 else "退！"\nprint(status)\n\n# 嵌入 f-string\nprint(f"血气 {hp}：{\'充足\' if hp>=50 else \'不足\'}")',
      output: '退！\n血气 40：不足',
      note: '三元表达式适合简单的二选一；复杂逻辑请用完整 if/else，不要强行压缩。',
      related: ['py-if-else'],
      story: '战局瞬息万变，一息之间，决断已出！',
    },
    {
      id: 'a4-c5', type: 'challenge', topicId: 'py-ternary', missionId: 'a4-m5',
      title: '一息决断',
      story: '有马则骑马，无马则步行！',
      task: "horse=True\n用三元表达式：horse 为真时 transport='骑马'，否则 '步行'\n打印 transport。",
      starter: 'horse = True\n# 三元表达式赋值\n',
      expect: '骑马',
      hints: ["transport = '骑马' if horse else '步行'", 'print(transport)', '三元：值A if 条件 else 值B'],
      reward: '一息决断！三元表达式掌握。',
    },
    // ── BOSS: 七进七出 ─────────────────────────────────
    {
      id: 'a4-boss', type: 'boss', missionId: 'a4-boss',
      title: '七进七出（长坂坡）', bossName: '曹将文聘', bossTaunt: '赵云匹夫，今日必死在长坂！',
      story: '三道关卡，七进七出，护住阿斗！',
      lore: '正史（《三国志》）：赵云"身抱弱子"保全甘夫人与幼主，并非孤身杀入曹营取物。"七进七出"是演义夸张，但赵云的英勇是史实。夺青釭剑亦见于演义。',
      bossHp: 3,
      challenges: [
        { id: 'b1', task: 'hp=55；hp>50 时打印"突围冲锋！"，否则"护主撤退！"', starter: 'hp = 55\n', expect: '突围冲锋！', hint: 'if hp>50: print("突围冲锋！")\nelse: print("护主撤退！")' },
        { id: 'b2', task: 'rank="曹将"；用 elif 链：曹将→"斩！"，友军→"援！"，否则→"观！"', starter: 'rank = "曹将"\n', expect: '斩！', hint: 'if rank=="曹将": print("斩！")\nelif rank=="友军": print("援！")\nelse: print("观！")' },
        { id: 'b3', task: "救主成功=True；用三元打印 '幼主已护！' if True else '功败垂成…'", starter: 'rescued = True\n', expect: '幼主已护！', hint: "print('幼主已护！' if rescued else '功败垂成…')" },
      ],
      reward: '文聘退兵！赵云怀抱幼主，杀出重围！\n刘备赞："子龙，真吾虎将也！"\n牙门将军，实至名归！',
    },
  ],
}
