// 第五幕·截江夺斗 — 循环全套
export const ACT5 = {
  id: 'ch5', name: '第五幕·截江夺斗', emoji: '⚡', color: '#1A3A6B',
  subtitle: '210年，截江夺阿斗，连斩连追',
  blurb: '孙夫人欲携阿斗回东吴，赵云与张飞截江夺主——一骑当千、连斩连追的节奏，就是循环。',
  missions: [
    { id: 'a5-m1', title: '紧追不舍——while 循环', emoji: '🔄' },
    { id: 'a5-m2', title: '连斩斩将——for / range', emoji: '⚔️' },
    { id: 'a5-m3', title: '达成即收——break / continue', emoji: '🛑' },
    { id: 'a5-m4', title: '点将排序——enumerate / zip', emoji: '📋' },
    { id: 'a5-m5', title: '皆尽之时——loop else / pass', emoji: '✅' },
    { id: 'a5-m6', title: '多阵同攻——嵌套循环', emoji: '🌀' },
    { id: 'a5-boss', title: 'BOSS战·截江追击', emoji: '🌊' },
  ],
  steps: [
    // ── while ─────────────────────────────────────────
    {
      id: 'a5-t1', type: 'teach', topicId: 'py-while', missionId: 'a5-m1',
      title: 'while 循环',
      blurb: '只要条件为真，就不断重复执行——紧追到底！',
      syntax: 'while 条件:\n    循环体',
      example: 'n = 3\nwhile n > 0:\n    print(n)\n    n -= 1\nprint("冲锋！")',
      output: '3\n2\n1\n冲锋！',
      note: '务必在循环体内改变条件变量，否则死循环！Ctrl+C 可中断。',
      related: ['py-for-range', 'py-break-continue'],
      story: '追敌不停，直到距离为零！',
    },
    {
      id: 'a5-c1', type: 'challenge', topicId: 'py-while', missionId: 'a5-m1',
      title: '倒计时突围',
      story: '3、2、1——冲！',
      task: 'n=3，while 倒数，每行打印一个数字，最后打印"冲锋！"',
      starter: 'n = 3\n# while 循环倒数\n',
      expect: '3\n2\n1\n冲锋！',
      hints: ['while n >= 1:', '    print(n)\n    n -= 1', 'print("冲锋！")'],
      reward: '冲锋！while 循环掌握。',
    },
    // ── for / range ───────────────────────────────────
    {
      id: 'a5-t2', type: 'teach', topicId: 'py-for-range', missionId: 'a5-m2',
      title: 'for 循环与 range()',
      blurb: 'for 遍历序列（字符串/列表/range 等）中每个元素。',
      syntax: 'for 变量 in 序列:\n    循环体\n\nrange(stop)\nrange(start, stop)\nrange(start, stop, step)',
      example: 'for i in range(3):\n    print(f"第 {i+1} 击：斩！")\n\nfor ch in "龙胆":\n    print(ch)',
      output: '第 1 击：斩！\n第 2 击：斩！\n第 3 击：斩！\n龙\n胆',
      note: 'range(5) 产生 0,1,2,3,4（不含 5）；range(1,6) 产生 1~5。',
      related: ['py-while', 'py-enumerate-zip'],
      story: '连斩五将！for 循环一气呵成！',
    },
    {
      id: 'a5-c2', type: 'challenge', topicId: 'py-for-range', missionId: 'a5-m2',
      title: '连斩 COMBO',
      story: '一气连斩 5 次！',
      task: '用 for 循环打印 5 行，每行"斩！"',
      starter: '# for 循环打印 5 行"斩！"\n',
      expect: '斩！\n斩！\n斩！\n斩！\n斩！',
      hints: ['for i in range(5):', '    print("斩！")', 'range(5) 重复 5 次'],
      reward: 'COMBO ×5！for/range 掌握。',
    },
    // ── break / continue ──────────────────────────────
    {
      id: 'a5-t3', type: 'teach', topicId: 'py-break-continue', missionId: 'a5-m3',
      title: 'break / continue',
      blurb: 'break 立即退出循环；continue 跳过本次迭代，继续下一次。',
      syntax: 'break     # 退出整个循环\ncontinue  # 跳过本次，继续下轮',
      example: '# break：找到即止\nfor i in range(10):\n    if i == 3:\n        break\n    print(i)\n\n# continue：跳过偶数\nfor i in range(5):\n    if i % 2 == 0:\n        continue\n    print(i)',
      output: '0\n1\n2\n1\n3',
      note: 'break 退出的是最内层循环；嵌套循环中，break 只退出当前层。',
      related: ['py-while', 'py-for-range'],
      story: '夺回阿斗，立即收兵！break 达成即收。',
    },
    {
      id: 'a5-c3', type: 'challenge', topicId: 'py-break-continue', missionId: 'a5-m3',
      title: '夺主收兵',
      story: '追到第 3 步就夺回了——立刻 break！',
      task: '循环 range(6)，当 i == 3 时 break，打印每次的 i（0,1,2,3）。',
      starter: '# for 循环，i==3 时 break\n',
      expect: '0\n1\n2\n3',
      hints: ['for i in range(6):', '    print(i)\n    if i == 3:\n        break', '先 print 再 break'],
      reward: '阿斗夺回！break 掌握。',
    },
    {
      id: 'a5-q1', type: 'quiz', missionId: 'a5-m3',
      question: 'continue 的作用是？',
      options: ['退出整个循环', '跳过本次迭代，继续下一轮', '暂停循环', '重启循环'],
      answer: 1,
      explain: 'continue 跳过当前次循环体的剩余代码，直接进入下一次迭代；break 才是退出整个循环。',
    },
    // ── enumerate / zip ───────────────────────────────
    {
      id: 'a5-t4', type: 'teach', topicId: 'py-enumerate-zip', missionId: 'a5-m4',
      title: 'enumerate() 与 zip()',
      blurb: 'enumerate 在遍历时同时获取序号；zip 同时遍历多个序列。',
      syntax: 'enumerate(序列, start=0)  # 返回 (序号, 元素)\nzip(序列1, 序列2, ...)    # 返回配对元组',
      example: "heroes = ['赵云','张飞','关羽']\nfor i, h in enumerate(heroes, 1):\n    print(f'{i}. {h}')\n\nweapons = ['龙胆枪','蛇矛','青龙偃月刀']\nfor h, w in zip(heroes, weapons):\n    print(f'{h} → {w}')",
      output: '1. 赵云\n2. 张飞\n3. 关羽\n赵云 → 龙胆枪\n张飞 → 蛇矛\n关羽 → 青龙偃月刀',
      note: 'zip 以最短序列为准，超出部分自动截断。',
      related: ['py-for-range', 'py-list-basics'],
      story: '点将排座次，一一配上兵器！',
    },
    {
      id: 'a5-c4', type: 'challenge', topicId: 'py-enumerate-zip', missionId: 'a5-m4',
      title: '点将配器',
      story: '三将各配兵器，一一对应！',
      task: "heroes=['赵云','张飞','马超'], weapons=['龙胆枪','蛇矛','枪']\n用 zip 遍历，每行输出：姓名 → 武器",
      starter: "heroes = ['赵云','张飞','马超']\nweapons = ['龙胆枪','蛇矛','枪']\n# 用 zip 遍历输出\n",
      expect: '赵云 → 龙胆枪\n张飞 → 蛇矛\n马超 → 枪',
      hints: ['for h, w in zip(heroes, weapons):', "    print(f'{h} → {w}')", '注意箭头是中文 →'],
      reward: '点将配器完毕！zip 掌握。',
    },
    // ── loop else / pass ──────────────────────────────
    {
      id: 'a5-t5', type: 'teach', topicId: 'py-loop-else', missionId: 'a5-m5',
      title: 'loop else 与 pass',
      blurb: 'for/while 的 else 在循环正常结束（未被 break）时执行；pass 是空操作占位符。',
      syntax: 'for x in 序列:\n    ...\nelse:\n    # 未被 break 则执行\n\nif 条件:\n    pass  # 暂时留空',
      example: 'for i in range(3):\n    if i == 5:\n        break\nelse:\n    print("全程未中断")\n\nfor i in range(3):\n    pass  # 暂时不做任何事',
      output: '全程未中断',
      note: 'for…else 是 Python 独特语法；break 触发则 else 块跳过。',
      related: ['py-break-continue'],
      story: '追遍全营未见敌——全程清场完毕！',
    },
    {
      id: 'a5-c5', type: 'challenge', topicId: 'py-loop-else', missionId: 'a5-m5',
      title: '全营清场',
      story: '三营遍查，无一敌将——打印"清场完毕"！',
      task: '用 for i in range(3) 循环，不加 break；\n在 else 中打印"清场完毕"。',
      starter: '# for...else\n',
      expect: '清场完毕',
      hints: ['for i in range(3):', '    pass', 'else:\n    print("清场完毕")'],
      reward: '清场完毕！loop else 掌握。',
    },
    // ── 嵌套循环 ──────────────────────────────────────
    {
      id: 'a5-t6', type: 'teach', topicId: 'py-nested-loops', missionId: 'a5-m6',
      title: '嵌套循环',
      blurb: '循环里面可以再有循环——外层每跑一圈，内层完整跑完。',
      syntax: 'for i in range(外层):\n    for j in range(内层):\n        print(i, j)',
      example: 'for row in range(1, 3):\n    for col in range(1, 4):\n        print(f"({row},{col})", end=" ")\n    print()',
      output: '(1,1) (1,2) (1,3) \n(2,1) (2,2) (2,3) ',
      note: '嵌套循环时间复杂度是 O(n²)，数量大时注意性能。',
      related: ['py-for-range'],
      story: '两路兵马交叉扫荡——外层路，内层列！',
    },
    {
      id: 'a5-c6', type: 'challenge', topicId: 'py-nested-loops', missionId: 'a5-m6',
      title: '九宫格扫荡',
      story: '3×3 阵列逐格清扫！',
      task: '用嵌套 for 循环，打印 3×3 的乘法结果：\n1*1=1\n1*2=2\n...（3行，每行3个，每个独占一行）',
      starter: '# 嵌套循环打印 3x3\n',
      expect: '1*1=1\n1*2=2\n1*3=3\n2*1=2\n2*2=4\n2*3=6\n3*1=3\n3*2=6\n3*3=9',
      hints: ['for i in range(1,4):', '    for j in range(1,4):', '        print(f"{i}*{j}={i*j}")'],
      reward: '九宫扫荡！嵌套循环掌握。',
    },
    // ── BOSS ──────────────────────────────────────────
    {
      id: 'a5-boss', type: 'boss', missionId: 'a5-boss',
      title: '截江追击', bossName: '东吴将士周泰', bossTaunt: '阿斗已在船上，你还能追上？',
      story: '三题击破周泰，夺回幼主！',
      lore: '截江夺斗（210年），赵云与张飞追至船边，夺回刘禅。《三国志》记载赵云义正言辞，令孙夫人折服。',
      bossHp: 3,
      challenges: [
        { id: 'b1', task: '用 while：n=5，每次 print(n) 并 n-=1，直到 n<3 时 break', starter: 'n = 5\n', expect: '5\n4\n3', hint: 'while True:\n    print(n)\n    n-=1\n    if n<3: break' },
        { id: 'b2', task: "enumerate(['甲','乙','丙'], 1) 循环，每行输出：序号. 名字", starter: "lst=['甲','乙','丙']\n", expect: '1. 甲\n2. 乙\n3. 丙', hint: "for i,x in enumerate(lst,1):\n    print(f'{i}. {x}')" },
        { id: 'b3', task: '嵌套循环：外层 range(1,3)，内层 range(1,3)；每格打印 i*j，共 4 行', starter: '', expect: '1\n2\n2\n4', hint: 'for i in range(1,3):\n    for j in range(1,3):\n        print(i*j)' },
      ],
      reward: '周泰落败！幼主夺回，赵云威震江东！截江之功，史册留名。',
    },
  ],
}
