// 第六幕·平定桂阳·整编 — 数据结构全套
export const ACT6 = {
  id: 'ch6', name: '第六幕·平定桂阳·整编', emoji: '🏯', color: '#3A2A6E',
  subtitle: '210年，荆南平定，整编降卒',
  blurb: '赤壁后取荆南四郡，赵云平定桂阳，整编降卒、建立城池名册——数据结构是行军的仓库。',
  missions: [
    { id: 'a6-m1', title: '武器架——列表基础', emoji: '⚔️' },
    { id: 'a6-m2', title: '增兵减员——列表增删', emoji: '📝' },
    { id: 'a6-m3', title: '排兵布阵——列表排序遍历', emoji: '🔃' },
    { id: 'a6-m4', title: '铁律不变——元组', emoji: '🔒' },
    { id: 'a6-m5', title: '去重整编——集合', emoji: '🔘' },
    { id: 'a6-m6', title: '城池名册——字典基础', emoji: '📖' },
    { id: 'a6-m7', title: '遍查情报——字典遍历与嵌套', emoji: '🗺️' },
    { id: 'a6-m8', title: '快速整编——推导式', emoji: '⚡' },
    { id: 'a6-boss', title: 'BOSS战·大点验', emoji: '🏯' },
  ],
  steps: [
    // ── 列表基础 ──────────────────────────────────────
    {
      id: 'a6-t1', type: 'teach', topicId: 'py-list-basics', missionId: 'a6-m1',
      title: '列表 list',
      blurb: '列表是有序可变序列，用方括号 [] 创建，可存储任意类型。',
      syntax: 'lst = [值1, 值2, 值3]\nlst[0]        # 第一个元素\nlst[-1]       # 最后一个\nlen(lst)      # 长度',
      example: "weapons = ['龙胆枪', '宝剑', '盾牌']\nprint(weapons[0])\nprint(weapons[-1])\nprint(len(weapons))",
      output: '龙胆枪\n盾牌\n3',
      note: '列表元素可以是不同类型：[1, "赵云", True, [2,3]]（嵌套列表）。',
      related: ['py-list-methods', 'py-list-comprehension'],
      story: '武器架一字排开，一一点清！',
    },
    {
      id: 'a6-c1', type: 'challenge', topicId: 'py-list-basics', missionId: 'a6-m1',
      title: '武器点查',
      story: '点清武器架！',
      task: "weapons=['龙胆枪','宝剑','盾牌']\n打印第一件武器和列表总长度（各一行）。",
      starter: "weapons = ['龙胆枪', '宝剑', '盾牌']\n# 打印第一个元素和长度\n",
      expect: '龙胆枪\n3',
      hints: ['print(weapons[0])', 'print(len(weapons))', '索引从 0 开始'],
      reward: '武器点清！列表基础掌握。',
    },
    // ── 列表增删 ──────────────────────────────────────
    {
      id: 'a6-t2', type: 'teach', topicId: 'py-list-methods', missionId: 'a6-m2',
      title: '列表方法：增删改查',
      blurb: 'append/insert/extend 增加；remove/pop/del 删除。',
      syntax: 'lst.append(x)      # 尾部追加\nlst.insert(i, x)   # 指定位置插入\nlst.extend(lst2)   # 追加另一列表\nlst.remove(x)      # 删除首个 x\nlst.pop()          # 删除并返回最后一个\ndel lst[i]         # 删除指定位置',
      example: "bag = ['盾']\nbag.append('剑')\nbag.insert(0, '枪')\nprint(bag)\nbag.remove('盾')\nprint(bag)",
      output: "['枪', '盾', '剑']\n['枪', '剑']",
      note: 'pop() 返回被删元素，可用 x = lst.pop() 接收；remove 找不到值会报 ValueError。',
      related: ['py-list-basics', 'py-list-comprehension'],
      story: '缴获宝剑，入库！老旧盾牌，剔除！',
    },
    {
      id: 'a6-c2', type: 'challenge', topicId: 'py-list-methods', missionId: 'a6-m2',
      title: '入库出库',
      story: '加入宝剑，移除盾牌！',
      task: "bag=['龙胆枪','盾牌']\n用 append 加入 '宝剑'，用 remove 删除 '盾牌'，打印 bag。",
      starter: "bag = ['龙胆枪', '盾牌']\n# 修改 bag\n",
      expect: "['龙胆枪', '宝剑']",
      hints: ["bag.append('宝剑')", "bag.remove('盾牌')", 'print(bag)'],
      reward: '仓库整理好了！列表增删掌握。',
    },
    // ── 列表排序遍历 ──────────────────────────────────
    {
      id: 'a6-t3', type: 'teach', topicId: 'py-list-sort', missionId: 'a6-m3',
      title: '列表排序与遍历',
      blurb: 'sort() 原地排序；sorted() 返回新列表；for in 遍历。',
      syntax: 'lst.sort()              # 原地升序\nlst.sort(reverse=True)  # 原地降序\nsorted(lst)             # 返回新列表',
      example: "merits = [80, 30, 120, 50]\nmerits.sort()\nprint(merits)\nprint(sorted([3,1,2], reverse=True))\nfor m in merits:\n    print(m, end=' ')",
      output: '[30, 50, 80, 120]\n[3, 2, 1]\n30 50 80 120 ',
      note: 'sort() 修改原列表；sorted() 不修改原列表，更安全。',
      related: ['py-list-basics', 'py-for-range'],
      story: '战功从低到高排列——论功行赏！',
    },
    {
      id: 'a6-c3', type: 'challenge', topicId: 'py-list-sort', missionId: 'a6-m3',
      title: '论功行赏',
      story: '战功从大到小排序！',
      task: "merits=[80,30,120,50]\n用 sort(reverse=True) 降序排列，打印结果。",
      starter: "merits = [80, 30, 120, 50]\n# 降序排列并打印\n",
      expect: '[120, 80, 50, 30]',
      hints: ['merits.sort(reverse=True)', 'print(merits)', 'reverse=True 表示降序'],
      reward: '排名出炉！sort 掌握。',
    },
    // ── 元组 ──────────────────────────────────────────
    {
      id: 'a6-t4', type: 'teach', topicId: 'py-tuple', missionId: 'a6-m4',
      title: '元组 tuple',
      blurb: '元组与列表类似，但不可修改（immutable）——用于不变的数据。',
      syntax: 't = (值1, 值2, 值3)\nt = 值1, 值2    # 括号可省略\na, b = t        # 解包',
      example: "pos = (28, '常山', '白马')  # 年龄,出生地,坐骑\nprint(pos[0])\nprint(pos[1:])\na, b, c = pos\nprint(a, b, c)",
      output: '28\n(\'常山\', \'白马\')\n28 常山 白马',
      note: '元组不可修改，但可以解包（unpacking）；一个元素的元组要加逗号：(1,)。',
      related: ['py-list-basics'],
      story: '将领的籍贯、年龄——铁律不可更改！',
    },
    {
      id: 'a6-c4', type: 'challenge', topicId: 'py-tuple', missionId: 'a6-m4',
      title: '将档不可改',
      story: '赵云档案固定！',
      task: "创建元组 info = ('赵云', 28, '常山')\n解包到 name, age, hometown，打印：赵云 来自 常山",
      starter: "info = ('赵云', 28, '常山')\n# 解包并打印\n",
      expect: '赵云 来自 常山',
      hints: ['name, age, hometown = info', 'print(f"{name} 来自 {hometown}")', '解包顺序对应'],
      reward: '档案封存！元组解包掌握。',
    },
    {
      id: 'a6-q1', type: 'quiz', missionId: 'a6-m4',
      question: '以下哪句代码会报错？',
      options: ['t = (1, 2, 3); print(t[0])', 't = (1, 2, 3); t[0] = 9', 'a, b, c = (1, 2, 3)', "t = ('赵云',); print(t)"],
      answer: 1,
      explain: '元组不可修改（immutable），t[0]=9 会抛出 TypeError。其余操作均合法。',
    },
    // ── 集合 ──────────────────────────────────────────
    {
      id: 'a6-t5', type: 'teach', topicId: 'py-set', missionId: 'a6-m5',
      title: '集合 set',
      blurb: '集合自动去重，无序；支持并集 |、交集 &、差集 - 运算。',
      syntax: 's = {1, 2, 3}      # 创建\ns.add(4)           # 添加\ns.remove(2)        # 删除\nset(列表)           # 列表转集合（去重）',
      example: "降卒 = ['甲','乙','甲','丙','乙']\n已编 = set(降卒)\nprint(已编)\n\na = {1,2,3}\nb = {2,3,4}\nprint(a | b)  # 并集\nprint(a & b)  # 交集\nprint(a - b)  # 差集",
      output: "{'甲', '乙', '丙'}\n{1, 2, 3, 4}\n{2, 3}\n{1}",
      note: '集合是无序的，打印顺序不固定；不能用索引访问元素。',
      related: ['py-list-basics', 'py-dict-basics'],
      story: '降卒名单去重整编——集合自动完成！',
    },
    {
      id: 'a6-c5', type: 'challenge', topicId: 'py-set', missionId: 'a6-m5',
      title: '去重整编',
      story: '降卒名单有重复，去重后计数！',
      task: "soldiers=['甲','乙','甲','丙','乙','丙','丁']\n转成集合去重，打印集合的长度。",
      starter: "soldiers = ['甲','乙','甲','丙','乙','丙','丁']\n# 去重后打印长度\n",
      expect: '4',
      hints: ['unique = set(soldiers)', 'print(len(unique))', '去重后有 4 个不同元素'],
      reward: '去重完毕！集合 set 掌握。',
    },
    // ── 字典基础 ──────────────────────────────────────
    {
      id: 'a6-t6', type: 'teach', topicId: 'py-dict-basics', missionId: 'a6-m6',
      title: '字典 dict',
      blurb: '字典存储键值对（key:value），用花括号创建，通过 key 快速取值。',
      syntax: 'd = {key: value, ...}\nd[key]        # 取值\nd[key] = v    # 新增/修改\ndel d[key]    # 删除\nkey in d      # 检查 key',
      example: "cities = {'桂阳': 5000, '零陵': 3000}\nprint(cities['桂阳'])\ncities['武陵'] = 4000\nprint(len(cities))",
      output: '5000\n3',
      note: 'key 必须是不可变类型（字符串/数字/元组）；value 可以是任意类型。',
      related: ['py-dict-methods', 'py-set'],
      story: '城池名册一目了然——key=城名，value=守军数！',
    },
    {
      id: 'a6-c6', type: 'challenge', topicId: 'py-dict-basics', missionId: 'a6-m6',
      title: '查阅名册',
      story: '桂阳守军几何？',
      task: "cities={'桂阳':5000,'零陵':3000}\n打印 cities['桂阳'] 的值。",
      starter: "cities = {'桂阳': 5000, '零陵': 3000}\n# 打印桂阳的守军数\n",
      expect: '5000',
      hints: ["print(cities['桂阳'])", '用方括号 + 键名取值', '结果是 5000'],
      reward: '名册查阅！字典基础掌握。',
    },
    // ── 字典遍历与嵌套 ────────────────────────────────
    {
      id: 'a6-t7', type: 'teach', topicId: 'py-dict-methods', missionId: 'a6-m7',
      title: '字典遍历与嵌套',
      blurb: '.items() 同时遍历 key-value；.get() 安全取值；字典可嵌套字典。',
      syntax: 'd.keys()    # 所有键\nd.values()  # 所有值\nd.items()   # 所有键值对\nd.get(k, 默认值)  # 安全取值',
      example: "armies = {'骑兵':1000, '步兵':3000, '弓兵':500}\nfor unit, count in armies.items():\n    print(f'{unit}: {count}')\nprint(armies.get('水军', 0))  # 不存在返回 0",
      output: '骑兵: 1000\n步兵: 3000\n弓兵: 500\n0',
      note: '嵌套字典：d = {\'城A\': {\'守军\':1000, \'城主\':\'甲\'}}；用 d[\'城A\'][\'守军\'] 取值。',
      related: ['py-dict-basics', 'py-for-range'],
      story: '遍查各城情报，逐一汇总！',
    },
    {
      id: 'a6-c7', type: 'challenge', topicId: 'py-dict-methods', missionId: 'a6-m7',
      title: '城情汇报',
      story: '遍历各城守军，逐一汇报！',
      task: "cities={'桂阳':5000,'零陵':3000,'武陵':4000}\n用 items() 遍历，每行输出：城名: 守军数",
      starter: "cities = {'桂阳':5000, '零陵':3000, '武陵':4000}\n# 遍历并输出\n",
      expect: '桂阳: 5000\n零陵: 3000\n武陵: 4000',
      hints: ['for city, count in cities.items():', '    print(f"{city}: {count}")', '每行一城'],
      reward: '情报汇总！字典遍历掌握。',
    },
    // ── 推导式 ────────────────────────────────────────
    {
      id: 'a6-t8', type: 'teach', topicId: 'py-dict-comprehension', missionId: 'a6-m8',
      title: '列表与字典推导式',
      blurb: '用一行代码批量生成列表或字典——快速整编的秘诀。',
      syntax: '[表达式 for x in 序列 if 条件]  # 列表推导式\n{k:v for k,v in ...}            # 字典推导式',
      example: "# 列表推导式\nranks = [f'第{i}营' for i in range(1, 4)]\nprint(ranks)\n# 字典推导式\nsquares = {x: x**2 for x in range(1, 5)}\nprint(squares)\n# 带条件过滤\nevens = [x for x in range(10) if x%2==0]\nprint(evens)",
      output: "['第1营', '第2营', '第3营']\n{1: 1, 2: 4, 3: 9, 4: 16}\n[0, 2, 4, 6, 8]",
      note: '推导式比等效的 for 循环更简洁，但不要为了"炫技"而写难以阅读的复杂推导式。',
      related: ['py-list-basics', 'py-dict-basics'],
      story: '一令整编三营，推导式一气呵成！',
    },
    {
      id: 'a6-c8', type: 'challenge', topicId: 'py-dict-comprehension', missionId: 'a6-m8',
      title: '快速整编',
      story: '用推导式生成三营编制！',
      task: "用列表推导式生成 ['第1营','第2营','第3营']，打印。",
      starter: '# 列表推导式生成三营\n',
      expect: "['第1营', '第2营', '第3营']",
      hints: ["[f'第{i}营' for i in range(1,4)]", '推导式放在方括号里', 'print(...)'],
      reward: '整编完毕！推导式掌握。',
    },
    // ── BOSS ──────────────────────────────────────────
    {
      id: 'a6-boss', type: 'boss', missionId: 'a6-boss',
      title: '大点验', bossName: '校尉赵范（降将）', bossTaunt: '你能管好这整座城池的数据吗？',
      story: '桂阳太守赵范投降，须核查城中所有档案！',
      lore: '赵范降后，欲将寡嫂嫁给赵云，赵云以义辞之。史称赵云"以德服人"，桂阳百姓信服。',
      bossHp: 3,
      challenges: [
        { id: 'b1', task: "用推导式生成 [x**2 for x in range(1,5)]，打印", starter: '', expect: '[1, 4, 9, 16]', hint: 'print([x**2 for x in range(1,5)])' },
        { id: 'b2', task: "d={'骑兵':500,'步兵':2000}；用 items() 遍历打印 骑兵: 500 / 步兵: 2000", starter: "d={'骑兵':500,'步兵':2000}\n", expect: '骑兵: 500\n步兵: 2000', hint: "for k,v in d.items():\n    print(f'{k}: {v}')" },
        { id: 'b3', task: "lst=[1,2,2,3,3,3]；转集合去重，打印长度", starter: "lst=[1,2,2,3,3,3]\n", expect: '3', hint: 'print(len(set(lst)))' },
      ],
      reward: '赵范折服！大点验通过，桂阳入账。荆南四郡，尽归刘备！',
    },
  ],
}
