// 第七幕·入川取益州 — 函数全套
export const ACT7 = {
  id: 'ch7', name: '第七幕·入川取益州', emoji: '🏔️', color: '#1A5A3A',
  subtitle: '214年，克定益州，迁翊军将军',
  blurb: '赵云随诸葛亮、张飞入川，克定益州，迁翊军将军。函数是将招式封装成可反复施展的绝技。',
  extraTasks: [{
    id: 'a7-ex1',
    title: '无双招式·lambda排序',
    task: 'warriors = [("赵云",99),("张飞",95),("马超",93)]\n用一行 sorted + lambda 按武力值降序排列，打印第一名将领名。',
    starter: 'warriors = [("赵云",99),("张飞",95),("马超",93)]\n# sorted + lambda 排序后打印最强将领名\n',
    expect: '赵云',
    hints: ['sorted(warriors, key=lambda x: x[1], reverse=True)', '排序后 [0][0] 取名字', 'print(sorted(warriors, key=lambda x:x[1], reverse=True)[0][0])'],
    reward: '武力排名揭晓！赵云位列第一——无双将星，实至名归！',
  }],
  missions: [
    { id: 'a7-m1', title: '绝技成型——def / return', emoji: '⚔️' },
    { id: 'a7-m2', title: '因敌制宜——参数与默认参数', emoji: '🎯' },
    { id: 'a7-m3', title: '指名道姓——关键字参数', emoji: '🏷️' },
    { id: 'a7-m4', title: '万军之中——*args / **kwargs', emoji: '🌪️' },
    { id: 'a7-m5', title: '内外有别——作用域', emoji: '🔒' },
    { id: 'a7-m6', title: '一式绝技——lambda', emoji: '⚡' },
    { id: 'a7-m7', title: '过滤精兵——map / filter', emoji: '🔍' },
    { id: 'a7-m8', title: '剑走偏锋——递归（选）', emoji: '🌀' },
    { id: 'a7-boss', title: 'BOSS战·无双乱舞（招式连段）', emoji: '🏔️' },
  ],
  steps: [
    // ── def / return ──────────────────────────────────
    {
      id: 'a7-t1', type: 'teach', topicId: 'py-def', missionId: 'a7-m1',
      title: 'def 函数定义与 return',
      blurb: 'def 把一段逻辑命名封装，return 把结果交还调用者。',
      syntax: 'def 函数名(参数):\n    """说明（可选）"""\n    执行体\n    return 结果\n\n结果 = 函数名(参数)',
      example: 'def battle_cry(name):\n    return f"{name}，威震沙场！"\n\nprint(battle_cry("赵云"))\nprint(battle_cry("张飞"))',
      output: '赵云，威震沙场！\n张飞，威震沙场！',
      note: '没有 return 的函数返回 None；return 后的代码不再执行。',
      related: ['py-params', 'py-scope'],
      story: '把龙胆枪法封装成一招——随时施展！',
    },
    {
      id: 'a7-c1', type: 'challenge', topicId: 'py-def', missionId: 'a7-m1',
      title: '绝技封印',
      story: '定义函数，封印招式！',
      task: '定义函数 spell(word)，返回 word 两侧各加 "🚩" 的字符串。\n例：spell("龙胆") → "🚩龙胆🚩"\n调用 spell("龙胆") 并打印。',
      starter: 'def spell(word):\n    pass  # 补全\n\nprint(spell("龙胆"))\n',
      test: 'assert spell("龙胆") == "🚩龙胆🚩", "返回值不对"\nassert spell("子龙") == "🚩子龙🚩"\nprint("招式封印！")',
      hints: ['return "🚩" + word + "🚩"', '或用 f-string：f"🚩{word}🚩"', '删掉 pass 改写 return'],
      reward: '招式封印！def/return 掌握。',
    },
    // ── 参数 / 默认参数 ───────────────────────────────
    {
      id: 'a7-t2', type: 'teach', topicId: 'py-params', missionId: 'a7-m2',
      title: '参数与默认参数',
      blurb: '函数可以接收多个参数；默认参数在调用时可以省略。',
      syntax: 'def 函数名(必填, 可选=默认值):\n    ...',
      example: 'def attack(target, damage=50):\n    return f"攻击 {target}，造成 {damage} 伤害！"\n\nprint(attack("曹将"))       # 用默认 damage=50\nprint(attack("夏侯渊", 120))',
      output: '攻击 曹将，造成 50 伤害！\n攻击 夏侯渊，造成 120 伤害！',
      note: '默认参数必须放在必填参数后面；默认值在函数定义时计算一次。',
      related: ['py-def', 'py-keyword-args'],
      story: '因敌制宜——敌弱用普通招，敌强用绝技！',
    },
    {
      id: 'a7-c2', type: 'challenge', topicId: 'py-params', missionId: 'a7-m2',
      title: '招式强化',
      story: '定义招式函数，可选伤害值！',
      task: "定义 attack(target, damage=50)\n返回 f'攻击 {target}，造成 {damage} 伤害！'\n打印 attack('曹将')。",
      starter: "def attack(target, damage=50):\n    pass\n\nprint(attack('曹将'))\n",
      expect: '攻击 曹将，造成 50 伤害！',
      hints: ["return f'攻击 {target}，造成 {damage} 伤害！'", '删掉 pass', '调用时只传 target，damage 用默认值'],
      reward: '招式强化！默认参数掌握。',
    },
    // ── 关键字参数 ────────────────────────────────────
    {
      id: 'a7-t3', type: 'teach', topicId: 'py-keyword-args', missionId: 'a7-m3',
      title: '关键字参数',
      blurb: '调用时用 参数名=值 的形式，顺序可以不固定。',
      syntax: 'def 函数(a, b, c=0):\n    ...\n函数(c=3, a=1, b=2)  # 关键字调用',
      example: 'def report(name, rank="将军", merit=0):\n    print(f"{rank} {name}，战功 {merit}")\n\nreport("赵云", merit=680)           # rank 用默认，merit 指名\nreport(merit=300, name="张飞", rank="虎将")',
      output: '将军 赵云，战功 680\n虎将 张飞，战功 300',
      note: '关键字参数使代码更可读，尤其是参数多时；可与位置参数混用，但位置参数必须在前。',
      related: ['py-params', 'py-args-kwargs'],
      story: '指名道姓，调兵遣将，绝不混乱！',
    },
    {
      id: 'a7-c3', type: 'challenge', topicId: 'py-keyword-args', missionId: 'a7-m3',
      title: '指名点将',
      story: '用关键字参数点将，顺序随意！',
      task: '定义 greet(name, title="将军")，打印 f"{title} {name}"\n用关键字调用：greet(title="虎威将军", name="赵云")',
      starter: 'def greet(name, title="将军"):\n    print(f"{title} {name}")\n\ngreet(title="虎威将军", name="赵云")\n',
      expect: '虎威将军 赵云',
      hints: ['函数定义已给出', '直接运行即可', '关键字参数顺序可变'],
      reward: '指名点将！关键字参数掌握。',
    },
    // ── *args / **kwargs ──────────────────────────────
    {
      id: 'a7-t4', type: 'teach', topicId: 'py-args-kwargs', missionId: 'a7-m4',
      title: '*args 与 **kwargs',
      blurb: '*args 接收任意数量位置参数（元组）；**kwargs 接收任意关键字参数（字典）。',
      syntax: 'def func(*args, **kwargs):\n    print(args)    # 元组\n    print(kwargs)  # 字典',
      example: "def assemble(*heroes):\n    print(f'集结 {len(heroes)} 将：{\"、\".join(heroes)}')\n\nassemble('赵云', '张飞', '关羽')\nassemble('马超', '黄忠')",
      output: '集结 3 将：赵云、张飞、关羽\n集结 2 将：马超、黄忠',
      note: '按惯例用 *args / **kwargs 命名，但名字可以自定义（如 *names）。',
      related: ['py-keyword-args', 'py-tuple'],
      story: '万军之中——召集数量不定的英雄！',
    },
    {
      id: 'a7-c4', type: 'challenge', topicId: 'py-args-kwargs', missionId: 'a7-m4',
      title: '万军集结',
      story: '集结人数不定，*args 一网打尽！',
      task: '定义 total_troops(*counts)，返回所有 counts 求和。\n打印 total_troops(500, 1200, 800) 的结果。',
      starter: 'def total_troops(*counts):\n    pass\n\nprint(total_troops(500, 1200, 800))\n',
      test: 'assert total_troops(500, 1200, 800) == 2500\nassert total_troops(100) == 100\nassert total_troops() == 0\nprint("集结完毕！")',
      hints: ['return sum(counts)', '*counts 是一个元组', 'sum() 对元组求和'],
      reward: '万军集结！*args 掌握。',
    },
    {
      id: 'a7-q1', type: 'quiz', missionId: 'a7-m4',
      question: 'def f(*args) 中，args 的类型是？',
      options: ['list', 'tuple', 'dict', 'set'],
      answer: 1,
      explain: '*args 收集到的是一个 tuple（元组），不可修改；**kwargs 收集到的是 dict（字典）。',
    },
    // ── 作用域 ────────────────────────────────────────
    {
      id: 'a7-t5', type: 'teach', topicId: 'py-scope', missionId: 'a7-m5',
      title: '作用域 (Scope)',
      blurb: '函数内的变量是局部的，外部不可见；global 声明可读写全局变量。',
      syntax: 'x = 10  # 全局变量\ndef f():\n    y = 20  # 局部变量，外部不可见\n    global x\n    x = 99  # 修改全局',
      example: 'merit = 0  # 全局\ndef add_merit(n):\n    global merit\n    merit += n\n\nadd_merit(100)\nadd_merit(50)\nprint(merit)',
      output: '150',
      note: '优先使用参数传递和 return 值，而非 global——全局变量使代码难以维护。',
      related: ['py-def'],
      story: '帐内机密，外人不知——局部变量内外有别！',
    },
    {
      id: 'a7-c5', type: 'challenge', topicId: 'py-scope', missionId: 'a7-m5',
      title: '战功累积',
      story: '全局战功，从函数内部修改！',
      task: 'total = 0（全局变量）\n定义 earn(n)，用 global 修改 total，将 n 加入。\n调用 earn(200) 和 earn(150)，打印 total。',
      starter: 'total = 0\n\ndef earn(n):\n    pass  # 补全\n\nearn(200)\nearn(150)\nprint(total)\n',
      expect: '350',
      hints: ['global total', 'total += n', '最终 total = 350'],
      reward: '战功累积！global 作用域掌握。',
    },
    // ── lambda ────────────────────────────────────────
    {
      id: 'a7-t6', type: 'teach', topicId: 'py-lambda', missionId: 'a7-m6',
      title: 'lambda 匿名函数',
      blurb: 'lambda 是一行式匿名函数，适合简单的转换逻辑。',
      syntax: 'f = lambda 参数: 表达式\n# 等同于：\ndef f(参数):\n    return 表达式',
      example: 'double = lambda x: x * 2\nprint(double(5))\n\ncombo = lambda n: "斩！" * n\nprint(combo(3))\n\nheros = [("赵云",99),("张飞",95),("关羽",97)]\nheros.sort(key=lambda h: h[1], reverse=True)\nprint(heros)',
      output: '10\n斩！斩！斩！\n[(\'赵云\', 99), (\'关羽\', 97), (\'张飞\', 95)]',
      note: 'lambda 只能写一个表达式，不支持多行或 if/else 语句（可用三元表达式）。',
      related: ['py-def', 'py-map-filter'],
      story: '一招制敌——lambda 一行式绝技！',
    },
    {
      id: 'a7-c6', type: 'challenge', topicId: 'py-lambda', missionId: 'a7-m6',
      title: '无双连击',
      story: '无双槽满！一行定义连击招式！',
      task: '用 lambda 定义 musou：接受 n，返回 "斩！" 重复 n 次。\n打印 musou(4)。',
      starter: 'musou = lambda n: None  # 补全\nprint(musou(4))\n',
      test: 'assert musou(1) == "斩！"\nassert musou(4) == "斩！斩！斩！斩！"\nassert musou(0) == ""\nprint("无双乱舞！")',
      hints: ['lambda n: "斩！" * n', 'musou = lambda n: "斩！" * n', 'musou(4) 输出 4 个斩！'],
      reward: '无双连击！lambda 掌握。',
    },
    // ── map / filter ──────────────────────────────────
    {
      id: 'a7-t7', type: 'teach', topicId: 'py-map-filter', missionId: 'a7-m7',
      title: 'map() 与 filter()',
      blurb: 'map 对序列每个元素应用函数；filter 筛选满足条件的元素。',
      syntax: 'list(map(函数, 序列))\nlist(filter(函数, 序列))',
      example: 'merits = [30, 80, 50, 120, 10]\n# 战功翻倍\ndoubled = list(map(lambda x: x*2, merits))\nprint(doubled)\n# 筛选 > 50\nelite = list(filter(lambda x: x>50, merits))\nprint(elite)',
      output: '[60, 160, 100, 240, 20]\n[80, 120]',
      note: 'map/filter 返回迭代器，要用 list() 转换成列表才能打印。',
      related: ['py-lambda', 'py-list-basics'],
      story: '筛选精兵，战功翻倍——批量操作！',
    },
    {
      id: 'a7-c7', type: 'challenge', topicId: 'py-map-filter', missionId: 'a7-m7',
      title: '精兵筛选',
      story: '战功超过 60 的才是精锐！',
      task: "merits=[30,80,50,120,10]\n用 filter 筛选 > 60 的战功，转 list 后打印。",
      starter: "merits = [30, 80, 50, 120, 10]\n# filter 筛选\n",
      expect: '[80, 120]',
      hints: ['filter(lambda x: x>60, merits)', 'list(...) 转换', 'print(list(filter(...)))'],
      reward: '精兵选出！filter 掌握。',
    },
    // ── 递归 ──────────────────────────────────────────
    {
      id: 'a7-t8', type: 'teach', topicId: 'py-recursion', missionId: 'a7-m8',
      title: '递归（选学）',
      blurb: '函数调用自身——须有终止条件，否则无限循环。',
      syntax: 'def func(n):\n    if n == 0:    # 终止条件\n        return 1\n    return n * func(n-1)',
      example: 'def factorial(n):\n    if n <= 1:\n        return 1\n    return n * factorial(n-1)\n\nprint(factorial(5))   # 120 = 5!\nprint(factorial(1))   # 1',
      output: '120\n1',
      note: 'Python 默认递归深度限制 1000 层；深度递归应改用循环或 functools.lru_cache。',
      related: ['py-def', 'py-while'],
      story: '剑走偏锋——函数自身召唤自身，无限衍生！',
    },
    {
      id: 'a7-c8', type: 'challenge', topicId: 'py-recursion', missionId: 'a7-m8',
      title: '兵法阵图',
      story: '斐波那契数列——阵图如此循环！',
      task: '定义 fib(n)：n<=1 时返回 n，否则返回 fib(n-1)+fib(n-2)。\n打印 fib(7)。',
      starter: 'def fib(n):\n    pass\n\nprint(fib(7))\n',
      test: 'assert fib(0) == 0\nassert fib(1) == 1\nassert fib(7) == 13\nprint("阵图破解！")',
      hints: ['if n <= 1: return n', 'return fib(n-1) + fib(n-2)', 'fib(7) = 13'],
      reward: '阵图破解！递归掌握。',
    },
    // ── BOSS ──────────────────────────────────────────
    {
      id: 'a7-boss', type: 'boss', missionId: 'a7-boss',
      title: '无双乱舞（招式连段）', bossName: '益州守将刘璋麾下张任', bossTaunt: '汝能用函数之力破我阵法？',
      story: '三题连段，招招用函数，打破张任阵！',
      lore: '入川之战（214年），刘备军攻克成都，赵云迁翊军将军。张任是刘璋麾下名将，在落凤坡射杀庞统。',
      bossHp: 3,
      challenges: [
        { id: 'b1', task: '定义 double(x)，返回 x*2；打印 double(999)', starter: 'def double(x):\n    pass\nprint(double(999))\n', test: 'assert double(999)==1998\nprint("OK")', hint: 'return x*2' },
        { id: 'b2', task: '用 lambda 定义 power=接受 n 返回 2**n；打印 power(10)', starter: 'power = lambda n: None\nprint(power(10))\n', test: 'assert power(10)==1024\nprint("OK")', hint: 'lambda n: 2**n' },
        { id: 'b3', task: "merits=[10,60,80,120]；用 filter 筛选 >=60，打印 list 结果", starter: "merits=[10,60,80,120]\n", expect: '[60, 80, 120]', hint: 'print(list(filter(lambda x:x>=60, merits)))' },
      ],
      reward: '张任阵破！赵云招式连段，无双爆发！\n迁翊军将军——刘备麾下，赵云位列一方！',
    },
  ],
}
