// 第八幕·汉水空营·一身是胆 — import / 异常 / JSON
export const ACT8 = {
  id: 'ch8', name: '第八幕·汉水空营·一身是胆', emoji: '🎲', color: '#2A1A5E',
  subtitle: '219年，汉水之战，空营疑兵',
  blurb: '汉水之战，赵云兵少，大开营门偃旗息鼓，曹军疑有伏兵而退。刘备赞："子龙一身都是胆也！"军封"虎威将军"。',
  missions: [
    { id: 'a8-m1', title: '数术兵法——import math', emoji: '📐' },
    { id: 'a8-m2', title: '虚实之变——random + seed', emoji: '🎲' },
    { id: 'a8-m3', title: '天时地利——datetime', emoji: '📅' },
    { id: 'a8-m4', title: '中伏脱险——try / except', emoji: '🛡️' },
    { id: 'a8-m5', title: '进退皆谋——else / finally / raise', emoji: '⚖️' },
    { id: 'a8-m6', title: '传书往来——JSON', emoji: '📦' },
    { id: 'a8-boss', title: 'BOSS战·空营计（疑兵模拟）', emoji: '🎲' },
  ],
  steps: [
    // ── math ──────────────────────────────────────────
    {
      id: 'a8-t1', type: 'teach', topicId: 'py-import-math', missionId: 'a8-m1',
      title: 'import math',
      blurb: 'math 模块提供数学函数——开方、向下取整、圆周率等。',
      syntax: 'import math\nmath.sqrt(x)       # 平方根\nmath.floor(x)      # 向下取整\nmath.ceil(x)       # 向上取整\nmath.pi            # 3.14159...',
      example: 'import math\nprint(math.sqrt(144))   # 12.0\nprint(math.floor(7.8))  # 7\nprint(math.ceil(7.2))   # 8\nprint(round(math.pi, 3))',
      output: '12.0\n7\n8\n3.142',
      note: 'math.pow(2,10) 与 2**10 不同：前者返回 float，后者返回 int。',
      related: ['py-numbers', 'py-import-random'],
      story: '算兵布阵，须用数术——math 是军师的工具！',
    },
    {
      id: 'a8-c1', type: 'challenge', topicId: 'py-import-math', missionId: 'a8-m1',
      title: '算兵布阵',
      story: '多少人能站满 16 列阵？',
      task: 'import math\n打印 math.sqrt(16) 的结果。',
      starter: 'import math\n# 打印 math.sqrt(16)\n',
      expect: '4.0',
      hints: ['print(math.sqrt(16))', '结果是 4.0（float）', '不是 4，是 4.0'],
      reward: '阵法算清！math 掌握。',
    },
    // ── random ────────────────────────────────────────
    {
      id: 'a8-t2', type: 'teach', topicId: 'py-import-random', missionId: 'a8-m2',
      title: 'random 模块',
      blurb: 'random 提供伪随机数生成；seed() 固定随机序列，确保可重现。',
      syntax: 'import random\nrandom.seed(n)           # 固定种子\nrandom.randint(a, b)     # a~b 随机整数\nrandom.random()          # 0.0~1.0 随机浮点\nrandom.choice(序列)      # 随机取一个',
      example: "import random\nrandom.seed(0)\nprint(random.randint(1, 10))\nprint(random.choice(['突围','据守','诱敌']))",
      output: '6\n诱敌',
      note: '相同 seed 产生相同随机序列——测试时用 seed(0) 保证结果可重复。',
      related: ['py-import-math'],
      story: '战场虚实，随机应变——疑兵之计！',
    },
    {
      id: 'a8-c2', type: 'challenge', topicId: 'py-import-random', missionId: 'a8-m2',
      title: '疑兵布局',
      story: 'seed(0) 固定，randint >= 5 则曹军退！',
      task: 'import random\nrandom.seed(0)\n生成 randint(1,10)，若 >= 5 打印"曹军疑有伏兵，退！"，否则"曹军强攻！"',
      starter: 'import random\nrandom.seed(0)\n# 生成随机数后判断\n',
      expect: '曹军疑有伏兵，退！',
      hints: ['n = random.randint(1, 10)', 'if n >= 5:', '    print("曹军疑有伏兵，退！")'],
      reward: '空营计成！曹军退兵，赵云一身是胆！',
    },
    // ── datetime ──────────────────────────────────────
    {
      id: 'a8-t3', type: 'teach', topicId: 'py-import-datetime', missionId: 'a8-m3',
      title: 'datetime 模块',
      blurb: 'datetime 模块处理日期和时间——行军计日，天时在握。',
      syntax: 'from datetime import datetime, date\ntoday = date.today()           # 今日日期\nnow = datetime.now()           # 当前时刻\ntoday.strftime("%Y-%m-%d")     # 格式化',
      example: 'from datetime import date\ntoday = date.today()\nprint(f"今日：{today}")\nprint(f"年份：{today.year}")\nprint(f"月份：{today.month}")',
      output: '今日：2026-06-06\n年份：2026\n月份：6',
      note: 'strftime 格式符：%Y 四位年，%m 月，%d 日，%H 小时，%M 分，%S 秒。',
      related: ['py-str-fstring'],
      story: '行军计日——天时地利，知己知彼！',
    },
    {
      id: 'a8-c3', type: 'challenge', topicId: 'py-import-datetime', missionId: 'a8-m3',
      title: '计日成算',
      story: '打印今日年份！',
      task: 'from datetime import date\n打印 date.today().year（今年年份）。',
      starter: 'from datetime import date\n# 打印今年年份\n',
      test: 'from datetime import date\nresult = date.today().year\nassert date.today().year >= 2024, "年份不对"\nprint("天时在握！")',
      hints: ['print(date.today().year)', '结果是当前年份', '每次运行都是最新年份'],
      reward: '天时在握！datetime 掌握。',
    },
    // ── try / except ──────────────────────────────────
    {
      id: 'a8-t4', type: 'teach', topicId: 'py-try-except', missionId: 'a8-m4',
      title: 'try / except 异常处理',
      blurb: '把可能出错的代码放进 try，用 except 捕获并处理异常。',
      syntax: 'try:\n    危险操作\nexcept 异常类型 as e:\n    print("出错了:", e)\nexcept Exception:\n    print("通用处理")',
      example: 'try:\n    n = int("不是数字")\nexcept ValueError as e:\n    print(f"捕获错误: {e}")\n\ntry:\n    x = 1 / 0\nexcept ZeroDivisionError:\n    print("除零错误！")',
      output: '捕获错误: invalid literal for int() with base 10: \'不是数字\'\n除零错误！',
      note: '常见异常：ValueError / TypeError / ZeroDivisionError / IndexError / KeyError / FileNotFoundError。',
      related: ['py-try-else-finally', 'py-raise'],
      story: '中伏脱险——提前设好退路，临危不乱！',
    },
    {
      id: 'a8-c4', type: 'challenge', topicId: 'py-try-except', missionId: 'a8-m4',
      title: '识破陷阱',
      story: '敌人设下转换陷阱——用 try 识破！',
      task: '用 try/except 尝试 int("非数字")，\n捕获 ValueError，打印"识破陷阱，安然无恙！"',
      starter: '# try/except\n',
      expect: '识破陷阱，安然无恙！',
      hints: ['try:\n    int("非数字")', 'except ValueError:', '    print("识破陷阱，安然无恙！")'],
      reward: '中伏脱险！try/except 掌握。',
    },
    // ── else / finally / raise ────────────────────────
    {
      id: 'a8-t5', type: 'teach', topicId: 'py-try-else-finally', missionId: 'a8-m5',
      title: 'try…else / finally / raise',
      blurb: 'else 在无异常时执行；finally 无论如何都执行；raise 主动抛出异常。',
      syntax: 'try:\n    ...\nexcept 异常:\n    ...\nelse:\n    # 无异常时执行\nfinally:\n    # 始终执行（清理）',
      example: 'try:\n    x = int("42")\nexcept ValueError:\n    print("转换失败")\nelse:\n    print(f"成功：{x}")\nfinally:\n    print("无论如何：收兵！")',
      output: '成功：42\n无论如何：收兵！',
      note: 'raise ValueError("消息") 主动抛出异常；常用于参数校验。',
      related: ['py-try-except'],
      story: '进退皆谋——成功有奖励，失败有退路，收兵无论如何！',
    },
    {
      id: 'a8-c5', type: 'challenge', topicId: 'py-try-else-finally', missionId: 'a8-m5',
      title: '完整防御阵',
      story: '完整的 try-else-finally——三层防线！',
      task: '写 try 块尝试 int("99")，\nexcept ValueError 打印"失败"，\nelse 打印 "成功: 99"，\nfinally 打印"收兵！"',
      starter: '# try-else-finally\n',
      expect: '成功: 99\n收兵！',
      hints: ['try:\n    x = int("99")', 'else:\n    print(f"成功: {x}")', 'finally:\n    print("收兵！")'],
      reward: '三层防线！else/finally 掌握。',
    },
    {
      id: 'a8-q1', type: 'quiz', missionId: 'a8-m5',
      question: 'finally 块什么时候执行？',
      options: ['只在有异常时执行', '只在无异常时执行', '无论是否有异常都执行', '只在 return 时执行'],
      answer: 2,
      explain: 'finally 无论是否发生异常都会执行，常用于资源清理（关闭文件/连接等）。',
    },
    // ── JSON ──────────────────────────────────────────
    {
      id: 'a8-t6', type: 'teach', topicId: 'py-json', missionId: 'a8-m6',
      title: 'JSON 处理',
      blurb: 'json 模块在 Python 字典/列表 与 JSON 字符串之间互相转换。',
      syntax: 'import json\njson.dumps(obj)      # Python → JSON 字符串\njson.loads(s)        # JSON 字符串 → Python',
      example: 'import json\ndata = {"将军": "赵云", "战功": 680, "兵器": ["龙胆枪"]}\ns = json.dumps(data, ensure_ascii=False)\nprint(s)\nback = json.loads(s)\nprint(back["将军"])',
      output: '{"将军": "赵云", "战功": 680, "兵器": ["龙胆枪"]}\n赵云',
      note: 'ensure_ascii=False 让中文不被转义；indent=2 让 JSON 格式化缩进输出。',
      related: ['py-dict-basics', 'py-str-basic'],
      story: '传书往来——将情报打包成 JSON 发出，再解包读取！',
    },
    {
      id: 'a8-c6', type: 'challenge', topicId: 'py-json', missionId: 'a8-m6',
      title: '情报打包',
      story: '把战报字典转成 JSON，再读回来！',
      task: 'import json\ndata = {"将军":"赵云","战功":680}\n用 json.dumps(data, ensure_ascii=False) 转字符串，\n再用 json.loads() 还原，打印 back["将军"]。',
      starter: 'import json\ndata = {"将军":"赵云","战功":680}\n# dumps 后再 loads\n',
      expect: '赵云',
      hints: ['s = json.dumps(data, ensure_ascii=False)', 'back = json.loads(s)', 'print(back["将军"])'],
      reward: '情报打包解包！JSON 掌握。',
    },
    // ── BOSS ──────────────────────────────────────────
    {
      id: 'a8-boss', type: 'boss', missionId: 'a8-boss',
      title: '空营计（疑兵模拟）', bossName: '曹将曹仁', bossTaunt: '区区空营，岂能吓退本将！',
      story: '三题破阵，智退曹仁！',
      lore: '汉水之战（219年），赵云以少胜多。刘备视察战场后，赞"子龙一身都是胆也！"，遂号"虎威将军"。',
      bossHp: 3,
      challenges: [
        { id: 'b1', task: 'import math\n打印 math.floor(99.9) 和 math.ceil(99.1)（各一行）', starter: 'import math\n', expect: '99\n100', hint: 'print(math.floor(99.9))\nprint(math.ceil(99.1))' },
        { id: 'b2', task: "try: int('X')；except ValueError: 打印'X不是数字，暂避锋芒！'", starter: '', expect: 'X不是数字，暂避锋芒！', hint: "try:\n    int('X')\nexcept ValueError:\n    print('X不是数字，暂避锋芒！')" },
        { id: 'b3', task: "import json\nd={'胜':'空营计'}；dumps(ensure_ascii=False) 后 loads，打印 back['胜']", starter: "import json\nd={'胜':'空营计'}\n", expect: '空营计', hint: "s=json.dumps(d,ensure_ascii=False)\nback=json.loads(s)\nprint(back['胜'])" },
      ],
      reward: '曹仁退兵！汉水大胜，赵云威名震天下！虎威将军，当之无愧！',
    },
  ],
}
