// 第九幕·北伐·箕谷敛众 — 类与面向对象
export const ACT9 = {
  id: 'ch9', name: '第九幕·北伐·箕谷敛众', emoji: '🏛️', color: '#3A3A6E',
  subtitle: '228年，诸葛亮第一次北伐，赵云据箕谷',
  blurb: '诸葛亮北伐，赵云据箕谷为疑军，兵败而亲自断后、敛众固守，军资无所弃。这是他最后的战役。class 是建立部曲体系的方式。',
  missions: [
    { id: 'a9-m1', title: '创立部曲——class / __init__', emoji: '🏛️' },
    { id: 'a9-m2', title: '将领属性——属性与方法', emoji: '⚔️' },
    { id: 'a9-m3', title: '招式传承——继承 / super', emoji: '🎯' },
    { id: 'a9-m4', title: '各显神通——多态 / __str__', emoji: '🌟' },
    { id: 'a9-m5', title: '剑气无穷——迭代器（选）', emoji: '🔄' },
    { id: 'a9-boss', title: 'BOSS战·箕谷断后（class 组织部曲）', emoji: '🏛️' },
  ],
  steps: [
    // ── class / __init__ ──────────────────────────────
    {
      id: 'a9-t1', type: 'teach', topicId: 'py-class', missionId: 'a9-m1',
      title: 'class 与 __init__',
      blurb: 'class 定义类（模板），__init__ 是构造函数，实例化时自动调用。',
      syntax: 'class 类名:\n    def __init__(self, 参数):\n        self.属性 = 参数\n\n实例 = 类名(参数)',
      example: 'class General:\n    def __init__(self, name, power):\n        self.name = name\n        self.power = power\n\nzhao = General("赵云", 99)\nprint(zhao.name)\nprint(zhao.power)',
      output: '赵云\n99',
      note: 'self 代表实例本身，必须是第一个参数；实例化时不用传 self。',
      related: ['py-class-methods', 'py-inheritance'],
      story: '创立部曲——将领是类，士兵是实例！',
    },
    {
      id: 'a9-c1', type: 'challenge', topicId: 'py-class', missionId: 'a9-m1',
      title: '编练部曲',
      story: '创建将领类，实例化赵云！',
      task: '定义 class Soldier，__init__ 接收 name 和 hp，\n实例化 Soldier("赵云", 100)，打印 name 属性。',
      starter: 'class Soldier:\n    def __init__(self, name, hp):\n        pass  # 补全\n\nzhao = Soldier("赵云", 100)\nprint(zhao.name)\n',
      expect: '赵云',
      hints: ['self.name = name', 'self.hp = hp', '实例化后用 zhao.name 取值'],
      reward: '部曲成立！class/__init__ 掌握。',
    },
    // ── 属性与方法 ────────────────────────────────────
    {
      id: 'a9-t2', type: 'teach', topicId: 'py-class-methods', missionId: 'a9-m2',
      title: '实例属性与方法',
      blurb: '方法是类内的函数（第一个参数是 self）；可以读写实例属性。',
      syntax: 'class 类名:\n    def 方法(self, 参数):\n        self.属性 += 参数\n        return self.属性',
      example: 'class General:\n    def __init__(self, name, power):\n        self.name = name\n        self.power = power\n        self.merit = 0\n\n    def battle_cry(self):\n        return f"{self.name}！武力 {self.power}！"\n\n    def earn(self, n):\n        self.merit += n\n\nzhao = General("赵云", 99)\nprint(zhao.battle_cry())\nzhao.earn(200)\nprint(zhao.merit)',
      output: '赵云！武力 99！\n200',
      note: '方法可以修改实例的属性（状态）；这是面向对象编程的核心。',
      related: ['py-class', 'py-inheritance'],
      story: '将领不仅有名号，还有招式、战功——方法赋予对象行为！',
    },
    {
      id: 'a9-c2', type: 'challenge', topicId: 'py-class-methods', missionId: 'a9-m2',
      title: '施展绝技',
      story: '赵云发出战吼——调用方法！',
      task: '完善 General：battle_cry 返回 f"{self.name} 威震沙场！武力 {self.power}！"\n实例化 General("赵云", 99)，打印 battle_cry()。',
      starter: 'class General:\n    def __init__(self, name, power):\n        self.name = name\n        self.power = power\n    def battle_cry(self):\n        pass  # 补全\n\nzhao = General("赵云", 99)\nprint(zhao.battle_cry())\n',
      expect: '赵云 威震沙场！武力 99！',
      hints: ['return f"{self.name} 威震沙场！武力 {self.power}！"', '删掉 pass', '注意空格和感叹号'],
      reward: '战吼震天！实例方法掌握。',
    },
    // ── 继承 / super ──────────────────────────────────
    {
      id: 'a9-t3', type: 'teach', topicId: 'py-inheritance', missionId: 'a9-m3',
      title: '继承与 super()',
      blurb: '子类继承父类所有方法；super() 调用父类方法，避免重复代码。',
      syntax: 'class 子类(父类):\n    def __init__(self, ...):\n        super().__init__(...)\n        self.新属性 = ...',
      example: 'class General:\n    def __init__(self, name):\n        self.name = name\n    def report(self):\n        return f"{self.name} 在阵！"\n\nclass Cavalry(General):\n    def __init__(self, name):\n        super().__init__(name)\n        self.mount = "白马"\n    def charge(self):\n        return f"{self.name} 骑 {self.mount} 冲锋！"\n\nc = Cavalry("赵云")\nprint(c.report())\nprint(c.charge())',
      output: '赵云 在阵！\n赵云 骑 白马 冲锋！',
      note: 'super().__init__() 确保父类正确初始化；子类可以重写（override）父类方法。',
      related: ['py-class-methods', 'py-polymorphism'],
      story: '骑将传承将领之道，再加骑兵冲锋——继承精华！',
    },
    {
      id: 'a9-c3', type: 'challenge', topicId: 'py-inheritance', missionId: 'a9-m3',
      title: '招式传承',
      story: '骑将继承将领，再加冲锋！',
      task: '在 General 基础上定义 class Cavalry(General)，\n新增方法 charge()，返回 f"{self.name} 骑兵冲锋！势如破竹！"\n实例化 Cavalry("赵云") 并打印 charge()。',
      starter: 'class General:\n    def __init__(self, name):\n        self.name = name\n\nclass Cavalry(General):\n    def charge(self):\n        pass  # 补全\n\nc = Cavalry("赵云")\nprint(c.charge())\n',
      expect: '赵云 骑兵冲锋！势如破竹！',
      hints: ['return f"{self.name} 骑兵冲锋！势如破竹！"', 'Cavalry 括号里写 General', 'c.name 来自父类'],
      reward: '传承绝技！继承掌握。',
    },
    // ── 多态 / __str__ ────────────────────────────────
    {
      id: 'a9-t4', type: 'teach', topicId: 'py-polymorphism', missionId: 'a9-m4',
      title: '多态与 __str__',
      blurb: '不同子类对同名方法有不同实现（多态）；__str__ 定义对象的字符串表示。',
      syntax: 'class A:\n    def __str__(self):\n        return "A 的字符串"\n\nprint(str(a))  # 调用 __str__',
      example: 'class Weapon:\n    def damage(self):\n        return 0\n\nclass Spear(Weapon):\n    def damage(self):\n        return 100\n    def __str__(self):\n        return "龙胆枪（伤害100）"\n\nclass Sword(Weapon):\n    def damage(self):\n        return 80\n    def __str__(self):\n        return "宝剑（伤害80）"\n\nfor w in [Spear(), Sword()]:\n    print(w, "→ 伤害:", w.damage())',
      output: '龙胆枪（伤害100） → 伤害: 100\n宝剑（伤害80） → 伤害: 80',
      note: '__str__ 被 print() 和 str() 自动调用；类似的还有 __repr__（开发者视角的字符串）。',
      related: ['py-inheritance'],
      story: '各显神通——同一接口，不同实现！',
    },
    {
      id: 'a9-c4', type: 'challenge', topicId: 'py-polymorphism', missionId: 'a9-m4',
      title: '各显神通',
      story: '龙胆枪介绍自己——实现 __str__！',
      task: '定义 class Weapon，__init__ 接收 name 和 dmg，\n__str__ 返回 f"{name}（伤害{dmg}）"\n实例化 Weapon("龙胆枪", 100)，print 它。',
      starter: 'class Weapon:\n    def __init__(self, name, dmg):\n        self.name = name\n        self.dmg = dmg\n    def __str__(self):\n        pass  # 补全\n\nw = Weapon("龙胆枪", 100)\nprint(w)\n',
      expect: '龙胆枪（伤害100）',
      hints: ['return f"{self.name}（伤害{self.dmg}）"', '__str__ 被 print 自动调用', '删掉 pass'],
      reward: '__str__ 掌握！print 不再只显示地址。',
    },
    {
      id: 'a9-q1', type: 'quiz', missionId: 'a9-m4',
      question: 'class B(A) 中，B 是什么？',
      options: ['A 的父类', 'A 的子类（继承 A）', 'A 的实例', 'A 的方法'],
      answer: 1,
      explain: 'class B(A) 表示 B 继承自 A；A 是父类（超类），B 是子类。B 拥有 A 的所有方法。',
    },
    // ── 迭代器（选）──────────────────────────────────
    {
      id: 'a9-t5', type: 'teach', topicId: 'py-iterator', missionId: 'a9-m5',
      title: '迭代器（选学）',
      blurb: '实现 __iter__ 和 __next__ 方法，让对象可被 for 循环遍历。',
      syntax: 'class 类名:\n    def __iter__(self):\n        self.idx = 0\n        return self\n    def __next__(self):\n        if self.idx >= 上限:\n            raise StopIteration\n        val = 数据[self.idx]\n        self.idx += 1\n        return val',
      example: 'class Countdown:\n    def __init__(self, n):\n        self.n = n\n    def __iter__(self):\n        self.cur = self.n\n        return self\n    def __next__(self):\n        if self.cur <= 0:\n            raise StopIteration\n        val = self.cur\n        self.cur -= 1\n        return val\n\nfor v in Countdown(3):\n    print(v)',
      output: '3\n2\n1',
      note: 'StopIteration 信号让 for 循环知道迭代结束；也可用 yield 生成器简化。',
      related: ['py-class-methods', 'py-for-range'],
      story: '剑气绵延——迭代器让对象可像列表一样遍历！',
    },
    {
      id: 'a9-c5', type: 'challenge', topicId: 'py-iterator', missionId: 'a9-m5',
      title: '连击无尽',
      story: '实现一个可 for 循环的连击计数器！',
      task: '完善 class HitCounter：__iter__ 初始化 self.cur=self.n；\n__next__ 递减，<=0 时 StopIteration。\n用 for 遍历 HitCounter(3)，打印每次的值。',
      starter: 'class HitCounter:\n    def __init__(self, n):\n        self.n = n\n    def __iter__(self):\n        self.cur = self.n\n        return self\n    def __next__(self):\n        if self.cur <= 0:\n            raise StopIteration\n        val = self.cur\n        self.cur -= 1\n        return val\n\nfor v in HitCounter(3):\n    print(v)\n',
      expect: '3\n2\n1',
      hints: ['代码已经完整', '直接运行即可', '迭代器模式：__iter__ + __next__'],
      reward: '迭代器掌握！自定义对象可被 for 遍历。',
    },
    // ── BOSS ──────────────────────────────────────────
    {
      id: 'a9-boss', type: 'boss', missionId: 'a9-boss',
      title: '箕谷断后（class 组织部曲）', bossName: '魏将郭淮', bossTaunt: '诸葛亮兵败，汝一人断后，岂能阻我？',
      story: '三题凭 class 抵御，敛众而退，无一弃！',
      lore: '箕谷之战（228年），赵云兵败但"敛众固守，军资什物略无所弃"。诸葛亮感其义，赏赐悉让部曲。赵云卒于229年，追谥"顺平侯"。',
      bossHp: 3,
      challenges: [
        { id: 'b1', task: '完善 General.__init__：self.name=name, self.hp=hp\n实例化 General("赵云",100), 打印 name', starter: 'class General:\n    def __init__(self, name, hp):\n        pass\nzhao = General("赵云", 100)\nprint(zhao.name)\n', expect: '赵云', hint: 'self.name = name\nself.hp = hp' },
        { id: 'b2', task: '在 General 里加 battle_cry 方法，返回 f"{name} 断后！"\n打印 zhoa.battle_cry()', starter: 'class General:\n    def __init__(self, name):\n        self.name = name\n    def battle_cry(self):\n        pass\nzhao=General("赵云")\nprint(zhao.battle_cry())\n', expect: '赵云 断后！', hint: 'return f"{self.name} 断后！"' },
        { id: 'b3', task: '实现 __str__ 返回 f"将军 {name}"，print General("赵云")', starter: 'class General:\n    def __init__(self,name):\n        self.name=name\n    def __str__(self):\n        pass\nprint(General("赵云"))\n', expect: '将军 赵云', hint: 'return f"将军 {self.name}"' },
      ],
      reward: '郭淮退兵！赵云以寡敌众，敛众而归，无一弃！\n"子龙一身都是胆也"——此言不虚！',
    },
  ],
}
